daftarKategori = [
  ["0", "Category:0"],
  ["1_(number)", "Category:1 (number)"],
  ["10-polytopes", "10-polytopes"],
  ["3-manifolds", "3-manifolds"],
  ["4-manifolds", "4-manifolds"],
  ["5-polytopes", "5-polytopes"],
  ["6-polytopes", "6-polytopes"],
  ["7-polytopes", "7-polytopes"],
  ["8-polytopes", "8-polytopes"],
  ["9-polytopes", "9-polytopes"],
  ["Abelian_group_theory", "Abelian group theory"],
  ["Abelian_varieties", "Abelian varieties"],
  ["Abstract_algebra", "Abstract algebra"],
  ["Additive_categories", "Additive categories"],
  ["Additive_number_theory", "Additive number theory"],
  ["Adjoint_functors", "Adjoint functors"],
  ["Affine_geometry", "Affine geometry"],
  ["Algebra", "Algebra"],
  ["Algebra_stubs", "Algebra stubs"],
  ["Algebraic_K-theory", "Algebraic K-theory"],
  ["Algebraic_analysis", "Algebraic analysis"],
  ["Algebraic_combinatorics", "Algebraic combinatorics"],
  ["Algebraic_curves", "Algebraic curves"],
  ["Algebraic_geometry", "Algebraic geometry"],
  ["Algebraic_graph_theory", "Algebraic graph theory"],
  ["Algebraic_groups", "Algebraic groups"],
  ["Algebraic_homogeneous_spaces", "Algebraic homogeneous spaces"],
  ["Algebraic_logic", "Algebraic logic"],
  ["Algebraic_number_theory", "Algebraic number theory"],
  ["Algebraic_numbers", "Algebraic numbers"],
  ["Algebraic_structures", "Algebraic structures"],
  ["Algebraic_surfaces", "Algebraic surfaces"],
  ["Algebraic_topology", "Algebraic topology"],
  ["Algebraic_varieties", "Algebraic varieties"],
  ["Algebras", "Algebras"],
  ["Algorithmic_information_theory", "Algorithmic information theory"],
  ["Analysis_of_variance", "Analysis of variance"],
  ["Analytic_geometry", "Analytic geometry"],
  ["Analytic_number_theory", "Analytic number theory"],
  ["Ancient_Greek_mathematical_works", "Ancient Greek mathematical works"],
  ["Ancient_Roman_mathematics", "Ancient Roman mathematics"],
  ["Application-specific_graphs", "Application-specific graphs"],
  ["Applied_mathematics", "Applied mathematics"],
  ["Applied_mathematics_stubs", "Applied mathematics stubs"],
  ["Applied_probability", "Applied probability"],
  ["Approximation_theory", "Approximation theory"],
  ["Approximations", "Approximations"],
  ["Arbelos", "Arbelos"],
  ["Archimedean_solids", "Archimedean solids"],
  ["Area", "Area"],
  ["Arithmetic", "Arithmetic"],
  ["Arithmetic_functions", "Arithmetic functions"],
  ["Arithmetic_problems_of_plane_geometry", "Arithmetic problems of plane geometry"],
  ["Arithmetic_problems_of_solid_geometry", "Arithmetic problems of solid geometry"],
  ["Asymptotic_analysis", "Asymptotic analysis"],
  ["Automated_theorem_proving", "Automated theorem proving"],
  ["Automorphic_forms", "Automorphic forms"],
  ["Axiom_of_choice", "Axiom of choice"],
  ["Axioms_of_set_theory", "Axioms of set theory"],
  ["Babylonian_mathematics", "Babylonian mathematics"],
  ["Banach_algebras", "Banach algebras"],
  ["Banach_spaces", "Banach spaces"],
  ["Base-dependent_integer_sequences", "Base-dependent integer sequences"],
  ["Basic_concepts_in_infinite_set_theory", "Basic concepts in infinite set theory"],
  ["Basic_concepts_in_set_theory", "Basic concepts in set theory"],
  ["Bayesian_statistics", "Bayesian statistics"],
  ["Bifurcation_theory", "Bifurcation theory"],
  ["Bilinear_forms", "Bilinear forms"],
  ["Bilinear_maps", "Bilinear maps"],
  ["Binary_operations", "Binary operations"],
  ["Binary_polyhedral_groups", "Binary polyhedral groups"],
  ["Biographies_and_autobiographies_of_mathematicians", "Biographies and autobiographies of mathematicians"],
  ["Biorthogonal_wavelets", "Biorthogonal wavelets"],
  ["Bipyramids", "Bipyramids"],
  ["Birational_geometry", "Birational geometry"],
  ["Boolean_algebra", "Boolean algebra"],
  ["Boundary_conditions", "Boundary conditions"],
  ["Braid_groups", "Braid groups"],
  ["C*-algebras", "C*-algebras"],
  ["Calculus", "Calculus"],
  ["Calculus_of_variations", "Calculus of variations"],
  ["Capacity-approaching_codes", "Capacity-approaching codes"],
  ["Cardinal_numbers", "Cardinal numbers"],
  ["Catalan_solids", "Catalan solids"],
  ["Categorical_data", "Categorical data"],
  ["Categorical_logic", "Categorical logic"],
  ["Category_theory", "Category theory"],
  ["Category_theory_stubs", "Category theory stubs"],
  ["Categories_in_category_theory", "Categories in category theory"],
  ["Chaos_theory", "Chaos theory"],
  ["Chaotic_maps", "Chaotic maps"],
  ["Characteristic_classes", "Characteristic classes"],
  ["Characterization_of_probability_distributions", "Characterization of probability distributions"],
  ["Chinese_mathematics", "Chinese mathematics"],
  ["Chiral_polyhedra", "Chiral polyhedra"],
  ["Circle_packing", "Circle packing"],
  ["Circles", "Circles"],
  ["Circuit_complexity", "Circuit complexity"],
  ["Class_field_theory", "Class field theory"],
  ["Classes_of_prime_numbers", "Classes of prime numbers"],
  ["Classical_geometry", "Classical geometry"],
  ["Clifford_algebras", "Clifford algebras"],
  ["Closed_categories", "Closed categories"],
  ["Closure_operators", "Closure operators"],
  ["Coalgebras", "Coalgebras"],
  ["Coding_theory", "Coding theory"],
  ["Cohomology_theories", "Cohomology theories"],
  ["Combinatorial_algorithms", "Combinatorial algorithms"],
  ["Combinatorial_design", "Combinatorial design"],
  ["Combinatorial_game_theory", "Combinatorial game theory"],
  ["Combinatorial_group_theory", "Combinatorial group theory"],
  ["Combinatorial_optimization", "Combinatorial optimization"],
  ["Combinatorics", "Combinatorics"],
  ["Combinatorics_on_words", "Combinatorics on words"],
  ["Combinatorics_stubs", "Combinatorics stubs"],
  ["Combinatory_logic", "Combinatory logic"],
  ["Commutative_algebra", "Commutative algebra"],
  ["Compactification_(mathematics)", "Compactification (mathematics)"],
  ["Compactness_(mathematics)", "Compactness (mathematics)"],
  ["Compactness_theorems", "Compactness theorems"],
  ["Comparison_of_assessments", "Comparison of assessments"],
  ["Complex_analysis", "Complex analysis"],
  ["Complex_manifolds", "Complex manifolds"],
  ["Complex_numbers", "Complex numbers"],
  ["Complex_surfaces", "Complex surfaces"],
  ["Complexity_classes", "Complexity classes"],
  ["Computational_complexity_theory", "Computational complexity theory"],
  ["Computational_geometry", "Computational geometry"],
  ["Computational_group_theory", "Computational group theory"],
  ["Computational_hardness_assumptions", "Computational hardness assumptions"],
  ["Computational_number_theory", "Computational number theory"],
  ["Computational_problems_in_graph_theory", "Computational problems in graph theory"],
  ["Computational_resources", "Computational resources"],
  ["Computational_statistics", "Computational statistics"],
  ["Computational_statistics_journals", "Computational statistics journals"],
  ["Computational_topology", "Computational topology"],
  ["Computer_algebra", "Computer algebra"],
  ["Computer_arithmetic_algorithms", "Computer arithmetic algorithms"],
  ["Configurations_(geometry)", "Configurations (geometry)"],
  ["Conformal_geometry", "Conformal geometry"],
  ["Conformal_mappings", "Conformal mappings"],
  ["Conic_sections", "Conic sections"],
  ["Conjectures", "Conjectures"],
  ["Conjectures_about_prime_numbers", "Conjectures about prime numbers"],
  ["Connection_(mathematics)", "Connection (mathematics)"],
  ["Constructible_universe", "Constructible universe"],
  ["Constructivism_(mathematics)", "Constructivism (mathematics)"],
  ["Continued_fractions", "Continued fractions"],
  ["Continuous_distributions", "Continuous distributions"],
  ["Continuous_wavelets", "Continuous wavelets"],
  ["Continuum_theory", "Continuum theory"],
  ["Convergence_tests", "Convergence tests"],
  ["Convex_analysis", "Convex analysis"],
  ["Convex_geometry", "Convex geometry"],
  ["Coordinate_systems", "Coordinate systems"],
  ["Coordinate_systems_in_differential_geometry", "Coordinate systems in differential geometry"],
  ["Covariance_and_correlation", "Covariance and correlation"],
  ["Covering_lemmas", "Covering lemmas"],
  ["Coxeter_groups", "Coxeter groups"],
  ["Curvature_(mathematics)", "Curvature (mathematics)"],
  ["Curves", "Curves"],
  ["Cyclotomic_fields", "Cyclotomic fields"],
  ["Dagger_categories", "Dagger categories"],
  ["Decision-making_paradoxes", "Decision-making paradoxes"],
  ["Definitions_of_mathematical_integration", "Definitions of mathematical integration"],
  ["Deltahedra", "Deltahedra"],
  ["Descriptive_complexity", "Descriptive complexity"],
  ["Descriptive_set_theory", "Descriptive set theory"],
  ["Determinacy", "Determinacy"],
  ["Determinants", "Determinants"],
  ["Diagram_algebras", "Diagram algebras"],
  ["Diffeomorphisms", "Diffeomorphisms"],
  ["Differential_algebra", "Differential algebra"],
  ["Differential_calculus", "Differential calculus"],
  ["Differential_equations", "Differential equations"],
  ["Differential_forms", "Differential forms"],
  ["Differential_geometry", "Differential geometry"],
  ["Differential_geometry_of_surfaces", "Differential geometry of surfaces"],
  ["Differential_operators", "Differential operators"],
  ["Differential_structures", "Differential structures"],
  ["Differential_systems", "Differential systems"],
  ["Differential_topology", "Differential topology"],
  ["Differentiation_rules", "Differentiation rules"],
  ["Digital_topology", "Digital topology"],
  ["Dimension", "Dimension"],
  ["Dimension_theory", "Dimension theory"],
  ["Diophantine_approximation", "Diophantine approximation"],
  ["Diophantine_equations", "Diophantine equations"],
  ["Diophantine_geometry", "Diophantine geometry"],
  ["Directed_graphs", "Directed graphs"],
  ["Discrete_distributions", "Discrete distributions"],
  ["Discrete_geometry", "Discrete geometry"],
  ["Discrete_groups", "Discrete groups"],
  ["Discrete_mathematics", "Discrete mathematics"],
  ["Disproved_conjectures", "Disproved conjectures"],
  ["Divergent_series", "Divergent series"],
  ["Division_(mathematics)", "Division (mathematics)"],
  ["Divisor_function", "Divisor function"],
  ["Domain_decomposition_methods", "Domain decomposition methods"],
  ["Domain_theory", "Domain theory"],
  ["Duality_theories", "Duality theories"],
  ["Dynamic_programming", "Dynamic programming"],
  ["Dynamical_systems", "Dynamical systems"],
  ["Effective_descriptive_set_theory", "Effective descriptive set theory"],
  ["Egyptian_fractions", "Egyptian fractions"],
  ["Egyptian_mathematics", "Egyptian mathematics"],
  ["Elementary_algebra", "Elementary algebra"],
  ["Elementary_arithmetic", "Elementary arithmetic"],
  ["Elementary_geometry", "Elementary geometry"],
  ["Elementary_mathematics", "Elementary mathematics"],
  ["Elementary_number_theory", "Elementary number theory"],
  ["Elementary_special_functions", "Elementary special functions"],
  ["Elliptic_curves", "Elliptic curves"],
  ["Elliptic_functions", "Elliptic functions"],
  ["Elliptic_partial_differential_equations", "Elliptic partial differential equations"],
  ["Empirical_process", "Empirical process"],
  ["Enumerative_combinatorics", "Enumerative combinatorics"],
  ["Equations_of_fluid_dynamics", "Equations of fluid dynamics"],
  ["Ergodic_theory", "Ergodic theory"],
  ["Euclidean_geometry", "Euclidean geometry"],
  ["Euclidean_plane_geometry", "Euclidean plane geometry"],
  ["Euclidean_solid_geometry", "Euclidean solid geometry"],
  ["Euclidean_symmetries", "Euclidean symmetries"],
  ["Experimental_mathematics", "Experimental mathematics"],
  ["Exponentials", "Exponentials"],
  ["Extensions_and_generalizations_of_graphs", "Extensions and generalizations of graphs"],
  ["F-divergences", "F-divergences"],
  ["FFT_algorithms", "FFT algorithms"],
  ["Factorial_and_binomial_topics", "Factorial and binomial topics"],
  ["Faculty_of_Mathematics,_University_of_Cambridge", "Faculty of Mathematics, University of Cambridge"],
  ["Families_of_sets", "Families of sets"],
  ["Fiber_bundles", "Fiber bundles"],
  ["Fibonacci_numbers", "Fibonacci numbers"],
  ["Field_extensions", "Field extensions"],
  ["Field_(mathematics)", "Field (mathematics)"],
  ["Fields_of_mathematics", "Fields of mathematics"],
  ["Figurate_numbers", "Figurate numbers"],
  ["Finite_differences", "Finite differences"],
  ["Finite_fields", "Finite fields"],
  ["Finite_geometry", "Finite geometry"],
  ["Finite_groups", "Finite groups"],
  ["Finite_model_theory", "Finite model theory"],
  ["Finite_reflection_groups", "Finite reflection groups"],
  ["Finite_rings", "Finite rings"],
  ["Finsler_geometry", "Finsler geometry"],
  ["First_order_methods", "First order methods"],
  ["Fixed_points_(mathematics)", "Fixed points"],
  ["Foliations", "Foliations"],
  ["Forcing_(mathematics)", "Forcing"],
  ["Formal_systems", "Formal systems"],
  ["Formal_theories_of_arithmetic", "Formal theories of arithmetic"],
  ["Fourier_analysis", "Fourier analysis"],
  ["Fourier_series", "Fourier series"],
  ["Fractal_curves", "Fractal curves"],
  ["Fractals", "Fractals"],
  ["Fractional_calculus", "Fractional calculus"],
  ["Fractions_(mathematics)", "Fractions (mathematics)"],
  ["Fredholm_theory", "Fredholm theory"],
  ["Free_algebraic_structures", "Free algebraic structures"],
  ["Free_probability_theory", "Free probability theory"],
  ["French_mathematical_seminars", "French mathematical seminars"],
  ["Functional_analysis", "Functional analysis"],
  ["Functional_calculus", "Functional calculus"],
  ["Functional_equations", "Functional equations"],
  ["Functional_subgroups", "Functional subgroups"],
  ["Functions_and_mappings", "Functions and mappings"],
  ["Functors", "Functors"],
  ["Galois_theory", "Galois theory"],
  ["Gambling_mathematics", "Gambling mathematics"],
  ["Gamma_and_related_functions", "Gamma and related functions"],
  ["General_topology", "General topology"],
  ["Generalizations_of_the_derivative", "Generalizations of the derivative"],
  ["Generalized_functions", "Generalized functions"],
  ["Generalized_manifolds", "Generalized manifolds"],
  ["Generating_functions", "Generating functions"],
  ["Geometric_algebra", "Geometric algebra"],
  ["Geometric_algorithms", "Geometric algorithms"],
  ["Geometric_flow", "Geometric flow"],
  ["Geometric_graph_theory", "Geometric graph theory"],
  ["Geometric_graphs", "Geometric graphs"],
  ["Geometric_group_theory", "Geometric group theory"],
  ["Geometric_shapes", "Geometric shapes"],
  ["Geometric_topology", "Geometric topology"],
  ["Geometry", "Geometry"],
  ["Geometry_of_divisors", "Geometry of divisors"],
  ["Geometry_of_numbers", "Geometry of numbers"],
  ["Geometry_stubs", "Geometry stubs"],
  ["Glossaries_of_mathematics", "Glossaries of mathematics"],
  ["Golden_ratio", "Golden ratio"],
  ["Graph_algorithms", "Graph algorithms"],
  ["Graph_coloring", "Graph coloring"],
  ["Graph_connectivity", "Graph connectivity"],
  ["Graph_enumeration", "Graph enumeration"],
  ["Graph_families", "Graph families"],
  ["Graph_invariants", "Graph invariants"],
  ["Graph_operations", "Graph operations"],
  ["Graph_products", "Graph products"],
  ["Graph_theory", "Graph theory"],
  ["Graph_theory_objects", "Graph theory objects"],
  ["Graphical_concepts_in_set_theory", "Graphical concepts in set theory"],
  ["Graphical_models", "Graphical models"],
  ["Graphical_projections", "Graphical projections"],
  ["Graphs", "Graphs"],
  ["Greek_mathematics", "Greek mathematics"],
  ["Group_actions", "Group actions"],
  ["Group_automorphisms", "Group automorphisms"],
  ["Group_theory", "Group theory"],
  ["Hardy_spaces", "Hardy spaces"],
  ["Harmonic_analysis", "Harmonic analysis"],
  ["Harmonic_functions", "Harmonic functions"],
  ["Hierarchy_of_functions", "Hierarchy of functions"],
  ["Higher_category_theory", "Higher category theory"],
  ["Hilbert_spaces", "Hilbert spaces"],
  ["Hilbert%27s_problems", "Hilbert's problems"],
  ["Historical_treatment_of_quaternions", "Historical treatment of quaternions"],
  ["History_of_logic", "History of logic"],
  ["History_of_mathematics", "History of mathematics"],
  ["Hodge_theory", "Hodge theory"],
  ["Homeomorphisms", "Homeomorphisms"],
  ["Homogeneous_polynomials", "Homogeneous polynomials"],
  ["Homogeneous_spaces", "Homogeneous spaces"],
  ["Homological_algebra", "Homological algebra"],
  ["Homology_theory", "Homology theory"],
  ["Homotopy_theory", "Homotopy theory"],
  ["Honeycombs_(geometry)", "Honeycombs (geometry)"],
  ["Hopf_algebras", "Hopf algebras"],
  ["Hyperbolic_geometry", "Hyperbolic geometry"],
  ["Hyperbolic_partial_differential_equations", "Hyperbolic partial differential equations"],
  ["Hypercomplex_numbers", "Hypercomplex numbers"],
  ["Hypergeometric_functions", "Hypergeometric functions"],
  ["Hypergraphs", "Hypergraphs"],
  ["Ideals_(ring_theory)", "Ideals (ring theory)"],
  ["Incidence_geometry", "Incidence geometry"],
  ["Independence_(probability_theory)", "Independence (probability theory)"],
  ["Independence_results", "Independence results"],
  ["Indian_mathematics", "Indian mathematics"],
  ["Individual_graphs", "Individual graphs"],
  ["Infinite_graphs", "Infinite graphs"],
  ["Infinite_group_theory", "Infinite group theory"],
  ["Infinity", "Infinity"],
  ["Inner_model_theory", "Inner model theory"],
  ["Integer_factorization_algorithms", "Integer factorization algorithms"],
  ["Integer_sequences", "Integer sequences"],
  ["Integers", "Integers"],
  ["Integrable_systems", "Integrable systems"],
  ["Integral_calculus", "Integral calculus"],
  ["Integral_equations", "Integral equations"],
  ["Integral_geometry", "Integral geometry"],
  ["Integral_transforms", "Integral transforms"],
  ["Integrals", "Integrals"],
  ["Integration_on_manifolds", "Integration on manifolds"],
  ["International_Mathematical_Olympiad", "International Mathematical Olympiad"],
  ["Interpolation", "Interpolation"],
  ["Intersection_classes_of_graphs", "Intersection classes of graphs"],
  ["Intersection_theory", "Intersection theory"],
  ["Invariant_subspaces", "Invariant subspaces"],
  ["Invariant_theory", "Invariant theory"],
  ["Inverse_functions", "Inverse functions"],
  ["Inverse_problems", "Inverse problems"],
  ["Inversive_geometry", "Inversive geometry"],
  ["Irrational_numbers", "Irrational numbers"],
  ["Isomorphism_theorems", "Isomorphism theorems"],
  ["Japanese_mathematics", "Japanese mathematics"],
  ["Johnson_solids", "Johnson solids"],
  ["K-theory", "K-theory"],
  ["Kepler%E2%80%93Poinsot_polyhedra", "Kepler–Poinsot polyhedra"],
  ["Knot_theory", "Knot theory"],
  ["Lambda_calculus", "Lambda calculus"],
  ["Large_cardinals", "Large cardinals"],
  ["Large_integers", "Large integers"],
  ["Large_numbers", "Large numbers"],
  ["Latin_squares", "Latin squares"],
  ["Lattice_points", "Lattice points"],
  ["Lattice_theory", "Lattice theory"],
  ["Least_squares", "Least squares"],
  ["Lemmas", "Lemmas"],
  ["Lie_algebras", "Lie algebras"],
  ["Lie_groupoids", "Lie groupoids"],
  ["Lie_groups", "Lie groups"],
  ["Limit_sets", "Limit sets"],
  ["Limits_(mathematics)", "Limits"],
  ["Limits_(category_theory)", "Limits"],
  ["Linear_algebra", "Linear algebra"],
  ["Linear_operators", "Linear operators"],
  ["Linear_operators_in_calculus", "Linear operators in calculus"],
  ["Linear_programming", "Linear programming"],
  ["Lipschitz_maps", "Lipschitz maps"],
  ["Lists_of_mathematicians", "Lists of mathematicians"],
  ["Lists_of_things_named_after_mathematicians", "Lists of things named after mathematicians"],
  ["Localization_(mathematics)", "Localization (mathematics)"],
  ["Logarithms", "Logarithms"],
  ["Logic_books", "Logic books"],
  ["Logical_calculi", "Logical calculi"],
  ["Logical_connectives", "Logical connectives"],
  ["Lorentzian_manifolds", "Lorentzian manifolds"],
  ["Low-dimensional_topology", "Low-dimensional topology"],
  ["Low-discrepancy_sequences", "Low-discrepancy sequences"],
  ["Magic_squares", "Magic squares"],
  ["Manifolds", "Manifolds"],
  ["Map_projections", "Map projections"],
  ["Maps_of_manifolds", "Maps of manifolds"],
  ["Markov_chain_Monte_Carlo", "Markov chain Monte Carlo"],
  ["Markov_models", "Markov models"],
  ["Markov_networks", "Markov networks"],
  ["Martingale_theory", "Martingale theory"],
  ["Matching_(graph_theory)", "Matching (graph theory)"],
  ["Mathematical_analysis", "Mathematical analysis"],
  ["Mathematical_analysis_stubs", "Mathematical analysis stubs"],
  ["Mathematical_axioms", "Mathematical axioms"],
  ["Mathematical_chairs", "Mathematical chairs"],
  ["Mathematical_concepts", "Mathematical concepts"],
  ["Mathematical_congresses", "Mathematical congresses"],
  ["Mathematical_constants", "Mathematical constants"],
  ["Mathematical_databases", "Mathematical databases"],
  ["Mathematical_examples", "Mathematical examples"],
  ["Mathematical_games", "Mathematical games"],
  ["Mathematical_identities", "Mathematical identities"],
  ["Mathematical_institutes", "Mathematical institutes"],
  ["Mathematical_logic", "Mathematical logic"],
  ["Mathematical_logic_hierarchies", "Mathematical logic hierarchies"],
  ["Mathematical_logic_organizations", "Mathematical logic organizations"],
  ["Mathematical_logic_stubs", "Mathematical logic stubs"],
  ["Mathematical_modeling", "Mathematical modeling"],
  ["Mathematical_notation", "Mathematical notation"],
  ["Mathematical_objects", "Mathematical objects"],
  ["Mathematical_optimization", "Mathematical optimization"],
  ["Mathematical_paradoxes", "Mathematical paradoxes"],
  ["Mathematical_physics", "Mathematical physics"],
  ["Mathematical_principles", "Mathematical principles"],
  ["Mathematical_problems", "Mathematical problems"],
  ["Mathematical_proofs", "Mathematical proofs"],
  ["Mathematical_relations", "Mathematical relations"],
  ["Mathematical_science_occupations", "Mathematical science occupations"],
  ["Mathematical_societies", "Mathematical societies"],
  ["Mathematical_structures", "Mathematical structures"],
  ["Mathematical_symbols", "Mathematical symbols"],
  ["Mathematical_tables", "Mathematical tables"],
  ["Mathematical_terminology", "Mathematical terminology"],
  ["Mathematical_theorems", "Mathematical theorems"],
  ["Mathematical_tools", "Mathematical tools"],
  ["Mathematics", "Mathematics"],
  ["Mathematics_and_culture", "Mathematics and culture"],
  ["Mathematics_awards", "Mathematics awards"],
  ["Mathematics_books", "Mathematics books"],
  ["Mathematics_competition_stubs", "Mathematics competition stubs"],
  ["Mathematics_competitions", "Mathematics competitions"],
  ["Mathematics_conferences", "Mathematics conferences"],
  ["Mathematics_disambiguation_pages", "Mathematics disambiguation pages"],
  ["Mathematics_education", "Mathematics education"],
  ["Mathematics_education_reform", "Mathematics education reform"],
  ["Mathematics_education_television_series", "Mathematics education television series"],
  ["Mathematics_fiction_books", "Mathematics fiction books"],
  ["Mathematics_in_the_medieval_Islamic_world", "Mathematics in the medieval Islamic world"],
  ["Mathematics_journals", "Mathematics journals"],
  ["Mathematics_literature", "Mathematics literature"],
  ["Mathematics_literature_stubs", "Mathematics literature stubs"],
  ["Mathematics_manuscripts", "Mathematics manuscripts"],
  ["Mathematics_of_computing", "Mathematics of computing"],
  ["Mathematics_of_rigidity", "Mathematics of rigidity"],
  ["Mathematics_organizations", "Mathematics organizations"],
  ["Mathematics_papers", "Mathematics papers"],
  ["Mathematics_stubs", "Mathematics stubs"],
  ["Mathematics_templates", "Mathematics templates"],
  ["Mathematics_timelines", "Mathematics timelines"],
  ["Mathematics_websites", "Mathematics websites"],
  ["Mathematics-related_lists", "Mathematics-related lists"],
  ["Matrix_decompositions", "Matrix decompositions"],
  ["Matrix_normal_forms", "Matrix normal forms"],
  ["Matrix_theory", "Matrix theory"],
  ["Matroid_theory", "Matroid theory"],
  ["Means", "Means"],
  ["Measure_theory", "Measure theory"],
  ["Measures_(measure_theory)", "Measures (measure theory)"],
  ["Measures_(set_theory)", "Measures (set theory)"],
  ["Mental_calculation", "Mental calculation"],
  ["Metatheorems", "Metatheorems"],
  ["Metric_geometry", "Metric geometry"],
  ["Millennium_Prize_Problems", "Millennium Prize Problems"],
  ["Minimal_surfaces", "Minimal surfaces"],
  ["Misuse_of_statistics", "Misuse of statistics"],
  ["Model_theory", "Model theory"],
  ["Modular_arithmetic", "Modular arithmetic"],
  ["Modular_forms", "Modular forms"],
  ["Module_theory", "Module theory"],
  ["Moduli_theory", "Moduli theory"],
  ["Monoidal_categories", "Monoidal categories"],
  ["Monte_Carlo_methods", "Monte Carlo methods"],
  ["Moonshine_theory", "Moonshine theory"],
  ["Morphisms", "Morphisms"],
  ["Morphisms_of_schemes", "Morphisms of schemes"],
  ["Morse_theory", "Morse theory"],
  ["Multi-dimensional_geometry", "Multi-dimensional geometry"],
  ["Multilinear_algebra", "Multilinear algebra"],
  ["Multiple_comparisons", "Multiple comparisons"],
  ["Multiplication", "Multiplication"],
  ["Multiplicative_functions", "Multiplicative functions"],
  ["Multivariable_calculus", "Multivariable calculus"],
  ["Multivariate_continuous_distributions", "Multivariate continuous distributions"],
  ["Multivariate_discrete_distributions", "Multivariate discrete distributions"],
  ["Multivariate_interpolation", "Multivariate interpolation"],
  ["Multivariate_statistics", "Multivariate statistics"],
  ["Network_flow_problem", "Network flow problem"],
  ["Nilpotent_groups", "Nilpotent groups"],
  ["Non-associative_algebra", "Non-associative algebra"],
  ["Non-associative_algebras", "Non-associative algebras"],
  ["Non-Euclidean_geometry", "Non-Euclidean geometry"],
  ["Non-Newtonian_calculus", "Non-Newtonian calculus"],
  ["Non-classical_logic", "Non-classical logic"],
  ["Non-parametric_Bayesian_methods", "Non-parametric Bayesian methods"],
  ["Non-parametric_statistics", "Non-parametric statistics"],
  ["Nonstandard_analysis", "Nonstandard analysis"],
  ["Non-standard_positional_numeral_systems", "Non-standard positional numeral systems"],
  ["Non-uniform_random_numbers", "Non-uniform random numbers"],
  ["Noncommutative_geometry", "Noncommutative geometry"],
  ["Nonconvex_polyhedra", "Nonconvex polyhedra"],
  ["Nonlinear_functional_analysis", "Nonlinear functional analysis"],
  ["Nonlinear_systems", "Nonlinear systems"],
  ["Nonparametric_regression", "Nonparametric regression"],
  ["Normal_forms_(logic)", "Normal forms (logic)"],
  ["Normality_tests", "Normality tests"],
  ["Normed_spaces", "Normed spaces"],
  ["Norms_(mathematics)", "Norms (mathematics)"],
  ["Number_stubs", "Number stubs"],
  ["Number_theoretic_algorithms", "Number theoretic algorithms"],
  ["Number_theory", "Number theory"],
  ["Number_theory_stubs", "Number theory stubs"],
  ["Numbers", "Numbers"],
  ["Numeral_systems", "Numeral systems"],
  ["Numerals", "Numerals"],
  ["Numerical_analysis", "Numerical analysis"],
  ["Numerical_differential_equations", "Numerical differential equations"],
  ["Numerical_linear_algebra", "Numerical linear algebra"],
  ["Objects_(category_theory)", "Objects (category theory)"],
  ["Octonions", "Octonions"],
  ["Operator_algebras", "Operator algebras"],
  ["Operator_theory", "Operator theory"],
  ["Optimization_algorithms_and_methods", "Optimization algorithms and methods"],
  ["Order_theory", "Order theory"],
  ["Ordered_algebraic_structures", "Ordered algebraic structures"],
  ["Ordered_groups", "Ordered groups"],
  ["Ordinal_numbers", "Ordinal numbers"],
  ["Ordinary_differential_equations", "Ordinary differential equations"],
  ["Orthogonal_polynomials", "Orthogonal polynomials"],
  ["Orthogonal_wavelets", "Orthogonal wavelets"],
  ["P-groups", "P-groups"],
  ["Parabolic_partial_differential_equations", "Parabolic partial differential equations"],
  ["Paradoxes_of_naive_set_theory", "Paradoxes of naive set theory"],
  ["Parametric_families_of_graphs", "Parametric families of graphs"],
  ["Parametric_statistics", "Parametric statistics"],
  ["Partial_differential_equations", "Partial differential equations"],
  ["Partial_fractions", "Partial fractions"],
  ["Particle_statistics", "Particle statistics"],
  ["Perfect_graphs", "Perfect graphs"],
  ["Permutation_groups", "Permutation groups"],
  ["Permutations", "Permutations"],
  ["Perturbation_theory", "Perturbation theory"],
  ["Philosophy_of_mathematics", "Philosophy of mathematics"],
  ["Pi", "Pi"],
  ["Pi_algorithms", "Pi algorithms"],
  ["Platonic_solids", "Platonic solids"],
  ["Point_processes", "Point processes"],
  ["Poisson_point_processes", "Poisson point processes"],
  ["Poker_probability", "Poker probability"],
  ["Polish_mathematics", "Polish mathematics"],
  ["Polychora", "Polychora"],
  ["Polyforms", "Polyforms"],
  ["Polygons", "Polygons"],
  ["Polyhedra", "Polyhedra"],
  ["Polyhedral_combinatorics", "Polyhedral combinatorics"],
  ["Polyhedral_compounds", "Polyhedral compounds"],
  ["Polyhedral_stellation", "Polyhedral stellation"],
  ["Polyhedron_stubs", "Polyhedron stubs"],
  ["Polynomials", "Polynomials"],
  ["Polytopes", "Polytopes"],
  ["Positional_numeral_systems", "Positional numeral systems"],
  ["Potential_theory", "Potential theory"],
  ["Predicate_logic", "Predicate logic"],
  ["Primality_tests", "Primality tests"],
  ["Prime_numbers", "Prime numbers"],
  ["Prismatoid_polyhedra", "Prismatoid polyhedra"],
  ["Probabilistic_complexity_classes", "Probabilistic complexity classes"],
  ["Probabilistic_inequalities", "Probabilistic inequalities"],
  ["Probability", "Probability"],
  ["Probability_and_statistics", "Probability and statistics"],
  ["Probability_assessment", "Probability assessment"],
  ["Probability_distributions", "Probability distributions"],
  ["Probability_interpretations", "Probability interpretations"],
  ["Probability_stubs", "Probability stubs"],
  ["Probability_theory", "Probability theory"],
  ["Probability_theory_paradoxes", "Probability theory paradoxes"],
  ["Projective_geometry", "Projective geometry"],
  ["Projective_polyhedra", "Projective polyhedra"],
  ["Proof_theory", "Proof theory"],
  ["Properties_of_Lie_algebras", "Properties of Lie algebras"],
  ["Properties_of_groups", "Properties of groups"],
  ["Properties_of_topological_spaces", "Properties of topological spaces"],
  ["Propositional_calculus", "Propositional calculus"],
  ["Pseudoprimes", "Pseudoprimes"],
  ["Pyramids_(geometry)", "Pyramids (geometry)"],
  ["Q-analogs", "Q-analogs"],
  ["Quadratic_forms", "Quadratic forms"],
  ["Quadratic_residue", "Quadratic residue"],
  ["Quadrics", "Quadrics"],
  ["Quadrilaterals", "Quadrilaterals"],
  ["Quantification_(science)", "Quantification (science)"],
  ["Quantum_Monte_Carlo", "Quantum Monte Carlo"],
  ["Quantum_complexity_theory", "Quantum complexity theory"],
  ["Quantum_groups", "Quantum groups"],
  ["Quasiregular_polyhedra", "Quasiregular polyhedra"],
  ["Quaternions", "Quaternions"],
  ["Ramsey_theory", "Ramsey theory"],
  ["Random_dynamical_systems", "Random dynamical systems"],
  ["Random_graphs", "Random graphs"],
  ["Random_matrices", "Random matrices"],
  ["Randomized_algorithms", "Randomized algorithms"],
  ["Rational_functions", "Rational functions"],
  ["Rational_numbers", "Rational numbers"],
  ["Real_algebraic_geometry", "Real algebraic geometry"],
  ["Real_analysis", "Real analysis"],
  ["Real_closed_field", "Real closed field"],
  ["Real_numbers", "Real numbers"],
  ["Recreational_mathematics", "Recreational mathematics"],
  ["Recurrence_relations", "Recurrence relations"],
  ["Reflection_groups", "Reflection groups"],
  ["Regression_analysis", "Regression analysis"],
  ["Regression_variable_selection", "Regression variable selection"],
  ["Regular_graphs", "Regular graphs"],
  ["Regular_polyhedra", "Regular polyhedra"],
  ["Representable_functors", "Representable functors"],
  ["Representation_theory", "Representation theory"],
  ["Representation_theory_of_Lie_algebras", "Representation theory of Lie algebras"],
  ["Representation_theory_of_Lie_groups", "Representation theory of Lie groups"],
  ["Representation_theory_of_algebraic_groups", "Representation theory of algebraic groups"],
  ["Representation_theory_of_finite_groups", "Representation theory of finite groups"],
  ["Representation_theory_of_groups", "Representation theory of groups"],
  ["Riemann_surfaces", "Riemann surfaces"],
  ["Riemannian_geometry", "Riemannian geometry"],
  ["Ring_theory", "Ring theory"],
  ["Root-finding_algorithms", "Root-finding algorithms"],
  ["Rotation_in_three_dimensions", "Rotation in three dimensions"],
  ["Rules_of_inference", "Rules of inference"],
  ["Runge%E2%80%93Kutta_methods", "Runge–Kutta methods"],
  ["Sampling_(statistics)", "Sampling (statistics)"],
  ["Sampling_techniques", "Sampling techniques"],
  ["Scheme_theory", "Scheme theory"],
  ["Schools_of_mathematics", "Schools of mathematics"],
  ["Self-dual_polyhedra", "Self-dual polyhedra"],
  ["Semigroup_theory", "Semigroup theory"],
  ["Separation_axioms", "Separation axioms"],
  ["Sequences_and_series", "Sequences and series"],
  ["Sequential_methods", "Sequential methods"],
  ["Series_of_mathematics_books", "Series of mathematics books"],
  ["Set_theory", "Set theory"],
  ["Set_theory_stubs", "Set theory stubs"],
  ["Set-theoretic_universes", "Set-theoretic universes"],
  ["Sets_of_real_numbers", "Sets of real numbers"],
  ["Several_complex_variables", "Several complex variables"],
  ["Sextic_curves", "Sextic curves"],
  ["Sheaf_theory", "Sheaf theory"],
  ["Sieve_theory", "Sieve theory"],
  ["Simplicial_sets", "Simplicial sets"],
  ["Singular_integrals", "Singular integrals"],
  ["Singular_value_decomposition", "Singular value decomposition"],
  ["Singularity_theory", "Singularity theory"],
  ["Smooth_functions", "Smooth functions"],
  ["Sobolev_spaces", "Sobolev spaces"],
  ["Solitons", "Solitons"],
  ["Solvable_groups", "Solvable groups"],
  ["Space-filling_polyhedra", "Space-filling polyhedra"],
  ["Sparse_matrices", "Sparse matrices"],
  ["Special_functions", "Special functions"],
  ["Special_hypergeometric_functions", "Special hypergeometric functions"],
  ["Spectral_sequences", "Spectral sequences"],
  ["Spectral_theory", "Spectral theory"],
  ["Spherical_trigonometry", "Spherical trigonometry"],
  ["Spirals", "Spirals"],
  ["Spiric_sections", "Spiric sections"],
  ["Splines_(mathematics)", "Splines (mathematics)"],
  ["Sporadic_groups", "Sporadic groups"],
  ["Stability_theory", "Stability theory"],
  ["Statistical_algorithms", "Statistical algorithms"],
  ["Statistical_awards", "Statistical awards"],
  ["Statistical_deviation_and_dispersion", "Statistical deviation and dispersion"],
  ["Statistical_distance", "Statistical distance"],
  ["Statistical_hypothesis_testing", "Statistical hypothesis testing"],
  ["Statistical_inequalities", "Statistical inequalities"],
  ["Statistical_laws", "Statistical laws"],
  ["Statistical_methods", "Statistical methods"],
  ["Statistical_paradoxes", "Statistical paradoxes"],
  ["Statistical_randomness", "Statistical randomness"],
  ["Statistical_tests", "Statistical tests"],
  ["Statistical_theory", "Statistical theory"],
  ["Statistics", "Statistics"],
  ["Statistics_books", "Statistics books"],
  ["Statistics_education", "Statistics education"],
  ["Statistics_journals", "Statistics journals"],
  ["Stochastic_control", "Stochastic control"],
  ["Stochastic_differential_equations", "Stochastic differential equations"],
  ["Stochastic_models", "Stochastic models"],
  ["Stochastic_optimization", "Stochastic optimization"],
  ["Stochastic_processes", "Stochastic processes"],
  ["Structural_complexity_theory", "Structural complexity theory"],
  ["Structures_on_manifolds", "Structures on manifolds"],
  ["Subgroup_properties", "Subgroup properties"],
  ["Subgroup_series", "Subgroup series"],
  ["Subharmonic_functions", "Subharmonic functions"],
  ["Substructural_logic", "Substructural logic"],
  ["Summability_methods", "Summability methods"],
  ["Summary_statistics", "Summary statistics"],
  ["Sumsets", "Sumsets"],
  ["Super_linear_algebra", "Super linear algebra"],
  ["Surfaces", "Surfaces"],
  ["Surgery_theory", "Surgery theory"],
  ["Symbolic_dynamics", "Symbolic dynamics"],
  ["Symmetric_functions", "Symmetric functions"],
  ["Symplectic_geometry", "Symplectic geometry"],
  ["Symplectic_topology", "Symplectic topology"],
  ["Systems_of_formal_logic", "Systems of formal logic"],
  ["Systems_of_probability_distributions", "Systems of probability distributions"],
  ["Systems_of_set_theory", "Systems of set theory"],
  ["Systolic_geometry", "Systolic geometry"],
  ["Tails_of_probability_distributions", "Tails of probability distributions"],
  ["Tauberian_theorems", "Tauberian theorems"],
  ["Tensors", "Tensors"],
  ["Tensors_in_general_relativity", "Tensors in general relativity"],
  ["Ternary_operations", "Ternary operations"],
  ["Tessellation", "Tessellation"],
  ["Theorems", "Theorems"],
  ["Theorems_in_geometry", "Theorems in geometry"],
  ["Theorems_in_statistics", "Theorems in statistics"],
  ["Theory_of_continuous_functions", "Theory of continuous functions"],
  ["Theory_of_probability_distributions", "Theory of probability distributions"],
  ["Theta_functions", "Theta functions"],
  ["Threefolds", "Threefolds"],
  ["Time_series_models", "Time series models"],
  ["Time%E2%80%93frequency_analysis", "Time–frequency analysis"],
  ["Topological_algebra", "Topological algebra"],
  ["Topological_dynamics", "Topological dynamics"],
  ["Topological_games", "Topological games"],
  ["Topological_graph_theory", "Topological graph theory"],
  ["Topological_groups", "Topological groups"],
  ["Topological_methods_of_algebraic_geometry", "Topological methods of algebraic geometry"],
  ["Topological_spaces", "Topological spaces"],
  ["Topological_vector_spaces", "Topological vector spaces"],
  ["Topology", "Topology"],
  ["Topology_of_Lie_groups", "Topology of Lie groups"],
  ["Topology_of_function_spaces", "Topology of function spaces"],
  ["Topology_of_homogeneous_spaces", "Topology of homogeneous spaces"],
  ["Topology_stubs", "Topology stubs"],
  ["Topos_theory", "Topos theory"],
  ["Toric_sections", "Toric sections"],
  ["Toroidal_polyhedra", "Toroidal polyhedra"],
  ["Traditional_mathematics", "Traditional mathematics"],
  ["Transcendental_numbers", "Transcendental numbers"],
  ["Transforms", "Transforms"],
  ["Trees_(graph_theory)", "Trees (graph theory)"],
  ["Trees_(set_theory)", "Trees (set theory)"],
  ["Triangle_geometry", "Triangle geometry"],
  ["Triangles", "Triangles"],
  ["Triangles_of_numbers", "Triangles of numbers"],
  ["Trigonometry", "Trigonometry"],
  ["Types_of_functions", "Types of functions"],
  ["Types_of_probability_distributions", "Types of probability distributions"],
  ["Uniform_polyhedra", "Uniform polyhedra"],
  ["Uniform_spaces", "Uniform spaces"],
  ["Unitary_operators", "Unitary operators"],
  ["Unitary_representation_theory", "Unitary representation theory"],
  ["Units_of_angle", "Units of angle"],
  ["Universal_algebra", "Universal algebra"],
  ["Unsolved_problems_in_mathematics", "Unsolved problems in mathematics"],
  ["Urelements", "Urelements"],
  ["Validity_(statistics)", "Validity (statistics)"],
  ["Vector_bundles", "Vector bundles"],
  ["Vector_calculus", "Vector calculus"],
  ["Vectors_(mathematics_and_physics)", "Vectors (mathematics and physics)"],
  ["Von_Neumann_algebras", "Von Neumann algebras"],
  ["Wavelets", "Wavelets"],
  ["Wellfoundedness", "Wellfoundedness"],
  ["Zeta_and_L-functions", "Zeta and L-functions"],
  ["Zonohedra", "Zonohedra"],
  ["10th-century_mathematicians", "10th-century mathematicians"],
  ["11th-century_mathematicians", "11th-century mathematicians"],
  ["12th-century_mathematicians", "12th-century mathematicians"],
  ["13th-century_mathematicians", "13th-century mathematicians"],
  ["14th-century_mathematicians", "14th-century mathematicians"],
  ["15th-century_mathematicians", "15th-century mathematicians"],
  ["16th-century_mathematicians", "16th-century mathematicians"],
  ["17th-century_mathematicians", "17th-century mathematicians"],
  ["18th-century_mathematicians", "18th-century mathematicians"],
  ["19th-century_mathematicians", "19th-century mathematicians"],
  ["20th-century_mathematicians", "20th-century mathematicians"],
  ["21st-century_mathematicians", "21st-century mathematicians"],
  ["5th-century_mathematicians", "5th-century mathematicians"],
  ["6th-century_mathematicians", "6th-century mathematicians"],
  ["7th-century_mathematicians", "7th-century mathematicians"],
  ["8th-century_mathematicians", "8th-century mathematicians"],
  ["9th-century_mathematicians", "9th-century mathematicians"],
  ["Abel_Prize_laureates", "Abel Prize laureates"],
  ["Abel_laureates", "Abel laureates"],
  ["African_mathematicians", "African mathematicians"],
  ["Albanian_mathematicians", "Albanian mathematicians"],
  ["Algebraic_geometers", "Algebraic geometers"],
  ["Algebraists", "Algebraists"],
  ["American_mathematician_stubs", "American mathematician stubs"],
  ["American_mathematicians", "American mathematicians"],
  ["Ancient_Greek_mathematicians", "Ancient Greek mathematicians"],
  ["Ancient_Indian_mathematicians", "Ancient Indian mathematicians"],
  ["Ancient_mathematicians", "Ancient mathematicians"],
  ["Argentine_mathematicians", "Argentine mathematicians"],
  ["Armenian_mathematicians", "Armenian mathematicians"],
  ["Asian_mathematician_stubs", "Asian mathematician stubs"],
  ["Australian_mathematicians", "Australian mathematicians"],
  ["Austrian_mathematicians", "Austrian mathematicians"],
  ["Azerbaijani_mathematicians", "Azerbaijani mathematicians"],
  ["Belarusian_mathematicians", "Belarusian mathematicians"],
  ["Belgian_mathematicians", "Belgian mathematicians"],
  ["Bengali_mathematicians", "Bengali mathematicians"],
  ["Bosnia_and_Herzegovina_mathematicians", "Bosnia and Herzegovina mathematicians"],
  ["Brazilian_mathematicians", "Brazilian mathematicians"],
  ["British_mathematicians", "British mathematicians"],
  ["Bulgarian_mathematicians", "Bulgarian mathematicians"],
  ["Cambridge_mathematicians", "Cambridge mathematicians"],
  ["Cameroonian_mathematicians", "Cameroonian mathematicians"],
  ["Canadian_mathematicians", "Canadian mathematicians"],
  ["Category_theorists", "Category theorists"],
  ["Chaos_theorists", "Chaos theorists"],
  ["Chilean_mathematicians", "Chilean mathematicians"],
  ["Chinese_mathematicians", "Chinese mathematicians"],
  ["Colombian_mathematicians", "Colombian mathematicians"],
  ["Combinatorial_game_theorists", "Combinatorial game theorists"],
  ["Croatian_mathematicians", "Croatian mathematicians"],
  ["Cuban_mathematicians", "Cuban mathematicians"],
  ["Czech_mathematicians", "Czech mathematicians"],
  ["Danish_mathematicians", "Danish mathematicians"],
  ["David_Crighton_medalists", "David Crighton medalists"],
  ["Differential_geometers", "Differential geometers"],
  ["Dutch_mathematicians", "Dutch mathematicians"],
  ["Egyptian_mathematicians", "Egyptian mathematicians"],
  ["English_mathematicians", "English mathematicians"],
  ["Estonian_mathematicians", "Estonian mathematicians"],
  ["European_mathematician_stubs", "European mathematician stubs"],
  ["Fields_Medalists", "Fields Medalists"],
  ["Finnish_mathematicians", "Finnish mathematicians"],
  ["French_mathematician_stubs", "French mathematician stubs"],
  ["French_mathematicians", "French mathematicians"],
  ["Functional_analysts", "Functional analysts"],
  ["Geometers", "Geometers"],
  ["Georgian_mathematicians", "Georgian mathematicians"],
  ["German_mathematician_stubs", "German mathematician stubs"],
  ["German_mathematicians", "German mathematicians"],
  ["Graph_theorists", "Graph theorists"],
  ["Greek_mathematicians", "Greek mathematicians"],
  ["Group_theorists", "Group theorists"],
  ["Historians_of_mathematics", "Historians of mathematics"],
  ["Hong_Kong_mathematicians", "Hong Kong mathematicians"],
  ["Hungarian_mathematicians", "Hungarian mathematicians"],
  ["Icelandic_mathematicians", "Icelandic mathematicians"],
  ["Indian_mathematicians", "Indian mathematicians"],
  ["Iranian_mathematicians", "Iranian mathematicians"],
  ["Iraqi_mathematicians", "Iraqi mathematicians"],
  ["Irish_mathematicians", "Irish mathematicians"],
  ["Israeli_mathematicians", "Israeli mathematicians"],
  ["Italian_mathematician_stubs", "Italian mathematician stubs"],
  ["Italian_mathematicians", "Italian mathematicians"],
  ["Japanese_mathematicians", "Japanese mathematicians"],
  ["Lattice_theorists", "Lattice theorists"],
  ["Latvian_mathematicians", "Latvian mathematicians"],
  ["Lithuanian_mathematicians", "Lithuanian mathematicians"],
  ["Maldivian_mathematicians", "Maldivian mathematicians"],
  ["Mathematical_analysts", "Mathematical analysts"],
  ["Mathematical_logicians", "Mathematical logicians"],
  ["Mathematician_stubs", "Mathematician stubs"],
  ["Mathematicians", "Mathematicians"],
  ["Mathematicians_by_century", "Mathematicians by century"],
  ["Mathematicians_by_field", "Mathematicians by field"],
  ["Mathematicians_by_nationality", "Mathematicians by nationality"],
  ["Mathematicians_from_Melbourne", "Mathematicians from Melbourne"],
  ["Mathematics_educators", "Mathematics educators"],
  ["Measure_theorists", "Measure theorists"],
  ["Medieval_mathematicians", "Medieval mathematicians"],
  ["Mexican_mathematicians", "Mexican mathematicians"],
  ["Model_theorists", "Model theorists"],
  ["Moldovan_mathematicians", "Moldovan mathematicians"],
  ["Moroccan_mathematicians", "Moroccan mathematicians"],
  ["New_Zealand_mathematicians", "New Zealand mathematicians"],
  ["Nigerian_mathematicians", "Nigerian mathematicians"],
  ["Norwegian_mathematicians", "Norwegian mathematicians"],
  ["Number_theorists", "Number theorists"],
  ["Numerical_analysts", "Numerical analysts"],
  ["Operator_theorists", "Operator theorists"],
  ["Pakistani_mathematicians", "Pakistani mathematicians"],
  ["Palestinian_mathematicians", "Palestinian mathematicians"],
  ["Polish_mathematician_stubs", "Polish mathematician stubs"],
  ["Polish_mathematicians", "Polish mathematicians"],
  ["Portuguese_mathematicians", "Portuguese mathematicians"],
  ["Probability_theorists", "Probability theorists"],
  ["Romanian_mathematicians", "Romanian mathematicians"],
  ["Russian_mathematician_stubs", "Russian mathematician stubs"],
  ["Russian_mathematicians", "Russian mathematicians"],
  ["Scottish_mathematicians", "Scottish mathematicians"],
  ["Serbian_mathematicians", "Serbian mathematicians"],
  ["Set_theorists", "Set theorists"],
  ["Mathematicians_from_Sicily", "Sicilian mathematicians"],
  ["Slovak_mathematicians", "Slovak mathematicians"],
  ["Slovenian_mathematicians", "Slovenian mathematicians"],
  ["South_African_mathematicians", "South African mathematicians"],
  ["Soviet_mathematicians", "Soviet mathematicians"],
  ["Spanish_mathematicians", "Spanish mathematicians"],
  ["Sri_Lankan_mathematicians", "Sri Lankan mathematicians"],
  ["Sudanese_mathematicians", "Sudanese mathematicians"],
  ["Swedish_mathematicians", "Swedish mathematicians"],
  ["Swiss_mathematicians", "Swiss mathematicians"],
  ["Syrian_mathematicians", "Syrian mathematicians"],
  ["Taiwanese_mathematicians", "Taiwanese mathematicians"],
  ["Tanzanian_mathematicians", "Tanzanian mathematicians"],
  ["Topologists", "Topologists"],
  ["Turkish_mathematicians", "Turkish mathematicians"],
  ["Ukrainian_mathematicians", "Ukrainian mathematicians"],
  ["Uruguayan_mathematicians", "Uruguayan mathematicians"],
  ["Vietnamese_mathematicians", "Vietnamese mathematicians"],
  ["Welsh_mathematicians", "Welsh mathematicians"],
  ["Wolf_Prize_in_Mathematics_laureates", "Wolf Prize in Mathematics laureates"],
  ["Women_mathematicians", "Women mathematicians"],
  ["Actuarial_associations", "Actuarial associations"],
  ["Actuarial_science", "Actuarial science"],
  ["Actuaries", "Actuaries"],
  ["Alan_Turing", "Alan Turing"],
  ["Algorithms", "Algorithms"],
  ["American_actuaries", "American actuaries"],
  ["American_cryptographers", "American cryptographers"],
  ["American_logicians", "American logicians"],
  ["American_statisticians", "American statisticians"],
  ["Analysis_of_algorithms", "Analysis of algorithms"],
  ["Angle", "Angle"],
  ["Applicative_computing_systems", "Applicative computing systems"],
  ["Applied_statistics", "Applied statistics"],
  ["Archimedes", "Archimedes"],
  ["Aristotle", "Aristotle"],
  ["Article_proofs", "Article proofs"],
  ["Articles_containing_proofs", "Articles containing proofs"],
  ["Artificial_life", "Artificial life"],
  ["Astronomical_dynamical_systems", "Astronomical dynamical systems"],
  ["Australian_cryptographers", "Australian cryptographers"],
  ["Australian_logicians", "Australian logicians"],
  ["Australian_statisticians", "Australian statisticians"],
  ["Austrian_cryptographers", "Austrian cryptographers"],
  ["Austrian_logicians", "Austrian logicians"],
  ["Automata", "Automata"],
  ["Automata_theory", "Automata theory"],
  ["Aviation_statistics", "Aviation statistics"],
  ["Ballistics_experts", "Ballistics experts"],
  ["Baseball_statistics", "Baseball statistics"],
  ["Basketball_statistics", "Basketball statistics"],
  ["Bayesian_networks", "Bayesian networks"],
  ["Belgian_logicians", "Belgian logicians"],
  ["Belgian_statisticians", "Belgian statisticians"],
  ["Bermuda_Triangle", "Bermuda Triangle"],
  ["Betting_systems", "Betting systems"],
  ["Bioinformatics", "Bioinformatics"],
  ["Biological_theorems", "Biological theorems"],
  ["Biostatisticians", "Biostatisticians"],
  ["Biostatistics", "Biostatistics"],
  ["Biostatistics_journals", "Biostatistics journals"],
  ["Blaise_Pascal", "Blaise Pascal"],
  ["Brahmagupta", "Brahmagupta"],
  ["Braids", "Braids"],
  ["Brazilian_logicians", "Brazilian logicians"],
  ["Brazilian_statisticians", "Brazilian statisticians"],
  ["British_actuaries", "British actuaries"],
  ["British_cryptographers", "British cryptographers"],
  ["British_logicians", "British logicians"],
  ["British_statisticians", "British statisticians"],
  ["Bubbles", "Bubbles"],
  ["Buddhist_logic", "Buddhist logic"],
  ["Buildings_and_structures_by_shape", "Buildings and structures by shape"],
  ["Bulgarian_logicians", "Bulgarian logicians"],
  ["Bulgarian_statisticians", "Bulgarian statisticians"],
  ["Calculators", "Calculators"],
  ["Canadian_actuaries", "Canadian actuaries"],
  ["Canadian_statisticians", "Canadian statisticians"],
  ["Celestial_coordinate_system", "Celestial coordinate system"],
  ["Cellular_automata", "Cellular automata"],
  ["Cellular_automata_in_popular_culture", "Cellular automata in popular culture"],
  ["Chaos_theory", "Chaos theory"],
  ["Character_encoding", "Character encoding"],
  ["Charts", "Charts"],
  ["Cheminformatics", "Cheminformatics"],
  ["Chinese_logicians", "Chinese logicians"],
  ["Cipher-machine_cryptographers", "Cipher-machine cryptographers"],
  ["Cluster_analysis", "Cluster analysis"],
  ["Cluster_analysis_algorithms", "Cluster analysis algorithms"],
  ["Coin_flipping", "Coin flipping"],
  ["Comparisons_of_mathematical_software", "Comparisons of mathematical software"],
  ["Computable_analysis", "Computable analysis"],
  ["Computational_models", "Computational models"],
  ["Computational_physics", "Computational physics"],
  ["Computational_problems", "Computational problems"],
  ["Computational_science", "Computational science"],
  ["Computer_algebra_systems", "Computer algebra systems"],
  ["Computer_arithmetic", "Computer arithmetic"],
  ["Computer_hardware_tuning", "Computer hardware tuning"],
  ["Computer_optimization", "Computer optimization"],
  ["Computer_science", "Computer science"],
  ["Computing", "Computing"],
  ["Conceptual_models", "Conceptual models"],
  ["Conservation_laws", "Conservation laws"],
  ["Constants", "Constants"],
  ["Control_devices", "Control devices"],
  ["Control_engineering", "Control engineering"],
  ["Control_theory", "Control theory"],
  ["Counting_instruments", "Counting instruments"],
  ["Critical_phenomena", "Critical phenomena"],
  ["Cross-sectional_analysis", "Cross-sectional analysis"],
  ["Cryptographers", "Cryptographers"],
  ["Cryptographers_by_nationality", "Cryptographers by nationality"],
  ["Cryptography", "Cryptography"],
  ["Cryptography_books", "Cryptography books"],
  ["Cryptography_contests", "Cryptography contests"],
  ["Cryptography_journals", "Cryptography journals"],
  ["Cryptography_stubs", "Cryptography stubs"],
  ["Cyberneticists", "Cyberneticists"],
  ["Cybernetics", "Cybernetics"],
  ["Czech_logicians", "Czech logicians"],
  ["Danish_statisticians", "Danish statisticians"],
  ["Data_analysis", "Data analysis"],
  ["Data_analysis_software", "Data analysis software"],
  ["Data_compression", "Data compression"],
  ["Data_differencing", "Data differencing"],
  ["Data_mining", "Data mining"],
  ["Decision_theory", "Decision theory"],
  ["Demographers", "Demographers"],
  ["Demography", "Demography"],
  ["Denotational_semantics", "Denotational semantics"],
  ["Descriptive_complexity", "Descriptive complexity"],
  ["Detection_theory", "Detection theory"],
  ["Dice", "Dice"],
  ["Digital_geometry", "Digital geometry"],
  ["Digital_signal_processing", "Digital signal processing"],
  ["Digital_systems", "Digital systems"],
  ["Digital_technology", "Digital technology"],
  ["Dimensional_analysis", "Dimensional analysis"],
  ["Dimensional_instruments", "Dimensional instruments"],
  ["Dimensionless_numbers", "Dimensionless numbers"],
  ["Documentary_television_series_about_mathematics", "Documentary television series"],
  ["Domes", "Domes"],
  ["Donald_Knuth", "Donald Knuth"],
  ["Dot_patterns", "Dot patterns"],
  ["Dutch_cryptographers", "Dutch cryptographers"],
  ["Dutch_logicians", "Dutch logicians"],
  ["Dutch_statisticians", "Dutch statisticians"],
  ["Econometric_models", "Econometric models"],
  ["Econometrics", "Econometrics"],
  ["Econometrics_journals", "Econometrics journals"],
  ["Econometrics_stubs", "Econometrics stubs"],
  ["Economic_data", "Economic data"],
  ["Economics", "Economics"],
  ["Economics_curves", "Economics curves"],
  ["Economics_theorems", "Economics theorems"],
  ["Egyptian_cryptographers", "Egyptian cryptographers"],
  ["Electrodynamics", "Electrodynamics"],
  ["Encyclopedias_of_mathematics", "Encyclopedias of mathematics"],
  ["English_logicians", "English logicians"],
  ["English_statisticians", "English statisticians"],
  ["Entropy", "Entropy"],
  ["Entropy_and_information", "Entropy and information"],
  ["Equations", "Equations"],
  ["Error", "Error"],
  ["Error_detection_and_correction", "Error detection and correction"],
  ["Estimation_theory", "Estimation theory"],
  ["Ethics_and_statistics", "Ethics and statistics"],
  ["Ethnomathematicians", "Ethnomathematicians"],
  ["Euclid", "Euclid"],
  ["Evolutionary_algorithms", "Evolutionary algorithms"],
  ["Exactly_solvable_models", "Exactly solvable models"],
  ["Experimental_design", "Experimental design"],
  ["Fellows_of_the_American_Statistical_Association", "Fellows of the American Statistical Association"],
  ["Fiction_about_cryptography", "Fiction about cryptography"],
  ["Fictional_dimensions", "Fictional dimensions"],
  ["Fictional_mathematicians", "Fictional mathematicians"],
  ["Filter_theory", "Filter theory"],
  ["Finger-counting", "Finger-counting"],
  ["Finite_element_method", "Finite element method"],
  ["Forensic_statistics", "Forensic statistics"],
  ["Formal_languages", "Formal languages"],
  ["Formal_methods", "Formal methods"],
  ["Formal_specification_languages", "Formal specification languages"],
  ["Frames_of_reference", "Frames of reference"],
  ["Free_Bayesian_statistics_software", "Free Bayesian statistics software"],
  ["French_cryptographers", "French cryptographers"],
  ["French_statisticians", "French statisticians"],
  ["Fundamental_constants", "Fundamental constants"],
  ["Fuzzy_logic", "Fuzzy logic"],
  ["GCHQ_cryptographers", "GCHQ cryptographers"],
  ["Game_theorists", "Game theorists"],
  ["Game_theory", "Game theory"],
  ["Genetic_algorithms", "Genetic algorithms"],
  ["Geographic_coordinate_systems", "Geographic coordinate systems"],
  ["Geometric_symbol_templates", "Geometric symbol templates"],
  ["Geostatistics", "Geostatistics"],
  ["German_logicians", "German logicians"],
  ["German_statisticians", "German statisticians"],
  ["Gottfried_Leibniz", "Gottfried Leibniz"],
  ["Graph_data_structures", "Graph data structures"],
  ["Graph_rewriting", "Graph rewriting"],
  ["Greek_logicians", "Greek logicians"],
  ["Hamiltonian_mechanics", "Hamiltonian mechanics"],
  ["Helices", "Helices"],
  ["Hungarian_statisticians", "Hungarian statisticians"],
  ["Icelandic_logicians", "Icelandic logicians"],
  ["Images_of_fractals", "Images of fractals"],
  ["Images_of_graphs", "Images of graphs"],
  ["Index_numbers", "Index numbers"],
  ["Indian_logicians", "Indian logicians"],
  ["Indian_statisticians", "Indian statisticians"],
  ["Information_theorists", "Information theorists"],
  ["Information_theory", "Information theory"],
  ["Institute_for_Advanced_Study", "Institute for Advanced Study"],
  ["Inter-rater_reliability", "Inter-rater reliability"],
  ["Interactive_evolutionary_computation", "Interactive evolutionary computation"],
  ["Interactive_geometry_software", "Interactive geometry software"],
  ["Irish_logicians", "Irish logicians"],
  ["Irish_statisticians", "Irish statisticians"],
  ["Isaac_Newton", "Isaac Newton"],
  ["Israel_Prize_in_exact_science_recipients", "Israel Prize in exact science recipients"],
  ["Israeli_cryptographers", "Israeli cryptographers"],
  ["Italian_cryptographers", "Italian cryptographers"],
  ["Jansenism", "Jansenism"],
  ["Japanese_logicians", "Japanese logicians"],
  ["Japanese_statisticians", "Japanese statisticians"],
  ["Jorge_Luis_Borges", "Jorge Luis Borges"],
  ["Kerala_school_of_astronomy_and_mathematics", "Kerala school of astronomy and mathematics"],
  ["Knot_stubs", "Knot stubs"],
  ["Knots", "Knots"],
  ["Length", "Length"],
  ["Leonardo_da_Vinci", "Leonardo da Vinci"],
  ["Lewis_Carroll", "Lewis Carroll"],
  ["Lists_of_ambiguous_numbers", "Lists of ambiguous numbers"],
  ["Logic", "Logic"],
  ["Logic_and_statistics", "Logic and statistics"],
  ["Logic_conferences", "Logic conferences"],
  ["Logic_in_computer_science", "Logic in computer science"],
  ["Logic_literature", "Logic literature"],
  ["Logic_puzzles", "Logic puzzles"],
  ["Logicians", "Logicians"],
  ["Logicians_by_nationality", "Logicians by nationality"],
  ["Lucasian_Professors_of_Mathematics", "Lucasian Professors of Mathematics"],
  ["Luck", "Luck"],
  ["M._C._Escher", "M. C. Escher"],
  ["Machine_learning", "Machine learning"],
  ["Machines", "Machines"],
  ["Mathematical_and_quantitative_methods_(economics)", "Mathematical and quantitative methods (economics)"],
  ["Mathematical_biology", "Mathematical biology"],
  ["Mathematical_chemistry", "Mathematical chemistry"],
  ["Mathematical_chess_problems", "Mathematical chess problems"],
  ["Mathematical_cognition_researchers", "Mathematical cognition researchers"],
  ["Mathematical_ecologists", "Mathematical ecologists"],
  ["Mathematical_economics", "Mathematical economics"],
  ["Mathematical_finance", "Mathematical finance"],
  ["Mathematical_formatting_templates", "Mathematical formatting templates"],
  ["Mathematical_function_templates", "Mathematical function templates"],
  ["Mathematical_markup_languages", "Mathematical markup languages"],
  ["Mathematical_optimization_software", "Mathematical optimization software"],
  ["Mathematical_physicists", "Mathematical physicists"],
  ["Mathematical_quantization", "Mathematical quantization"],
  ["Mathematical_software", "Mathematical software"],
  ["Mathematician_templates", "Mathematician templates"],
  ["Mathematics_awards_navigational_boxes", "Mathematics awards navigational boxes"],
  ["Mathematics_images", "Mathematics images"],
  ["Mathematics_of_music", "Mathematics of music"],
  ["Mathematics_source_templates", "Mathematics source templates"],
  ["Mathematics_stub_templates", "Mathematics stub templates"],
  ["Mathematics_templates", "Mathematics templates"],
  ["Mathematics_writers", "Mathematics writers"],
  ["Mechanical_calculators", "Mechanical calculators"],
  ["Mechanical_puzzles", "Mechanical puzzles"],
  ["Mechanics", "Mechanics"],
  ["Members_of_HM_Government_Statistical_Service", "Members of HM Government Statistical Service"],
  ["Mental_calculators", "Mental calculators"],
  ["Meta-analysis", "Meta-analysis"],
  ["Modal_logic", "Modal logic"],
  ["Model_checkers", "Model checkers"],
  ["Modern_cryptographers", "Modern cryptographers"],
  ["Molecular_geometry", "Molecular geometry"],
  ["Molecular_topology", "Molecular topology"],
  ["Monte_Carlo_software", "Monte Carlo software"],
  ["National_statistical_services", "National statistical services"],
  ["Network_performance", "Network performance"],
  ["Network_theory", "Network theory"],
  ["Network_topology", "Network topology"],
  ["Networks", "Networks"],
  ["Neural_networks", "Neural networks"],
  ["New_Zealand_statisticians", "New Zealand statisticians"],
  ["Niels_Henrik_Abel", "Niels Henrik Abel"],
  ["Noise", "Noise"],
  ["Non-equilibrium_thermodynamics", "Non-equilibrium thermodynamics"],
  ["Norwegian_actuaries", "Norwegian actuaries"],
  ["Norwegian_demographers", "Norwegian demographers"],
  ["Norwegian_statisticians", "Norwegian statisticians"],
  ["Number-related_lists", "Number-related lists"],
  ["Numerical_software", "Numerical software"],
  ["Numerology", "Numerology"],
  ["Nyaya", "Nyaya"],
  ["Operations_research", "Operations research"],
  ["Optimization_software", "Optimization software"],
  ["Orientation_(geometry)", "Orientation (geometry)"],
  ["Oscillation", "Oscillation"],
  ["Pakistani_statisticians", "Pakistani statisticians"],
  ["Paradoxes", "Paradoxes"],
  ["Parity_(mathematics)", "Parity (mathematics)"],
  ["Paul_Erd%C5%91s", "Paul Erdős"],
  ["Perspective_projection", "Perspective projection"],
  ["Pharmaceutical_statistics", "Pharmaceutical statistics"],
  ["Philosophers_of_mathematics", "Philosophers of mathematics"],
  ["Physics_theorems", "Physics theorems"],
  ["Pi_software", "Pi software"],
  ["Placeholder_names", "Placeholder names"],
  ["Polish_cryptographers", "Polish cryptographers"],
  ["Polish_logicians", "Polish logicians"],
  ["Polish_statisticians", "Polish statisticians"],
  ["Polyhedron_templates", "Polyhedron templates"],
  ["Population_statistics", "Population statistics"],
  ["Potentials", "Potentials"],
  ["Power_laws", "Power laws"],
  ["Precession", "Precession"],
  ["Presidents_of_statistical_organizations", "Presidents of statistical organizations"],
  ["Presidents_of_the_Associa%C3%A7%C3%A3o_Brasileira_de_Estat%C3%ADstica", "Presidents of the Associação Brasileira de Estatística"],
  ["Presidents_of_the_Royal_Statistical_Society", "Presidents of the Royal Statistical Society"],
  ["Presidents_of_the_Statistical_Society_of_Canada", "Presidents of the Statistical Society of Canada"],
  ["Process_calculi", "Process calculi"],
  ["Programming_language_theory_stubs", "Programming language theory stubs"],
  ["Pseudorandom_number_generators", "Pseudorandom number generators"],
  ["Psychometrics", "Psychometrics"],
  ["Public-key_cryptographers", "Public-key cryptographers"],
  ["Putnam_Fellows", "Putnam Fellows"],
  ["Pythagorean_philosophy", "Pythagorean philosophy"],
  ["Pythagorean_symbols", "Pythagorean symbols"],
  ["Pythagoreans", "Pythagoreans"],
  ["Quantum_field_theory", "Quantum field theory"],
  ["Quantum_mechanical_entropy", "Quantum mechanical entropy"],
  ["Quantum_mechanics", "Quantum mechanics"],
  ["Queueing_theorists", "Queueing theorists"],
  ["Queueing_theory", "Queueing theory"],
  ["Quotas", "Quotas"],
  ["Randomness", "Randomness"],
  ["Recreational_cryptographers", "Recreational cryptographers"],
  ["Recursion", "Recursion"],
  ["Relational_algebra", "Relational algebra"],
  ["Theory_of_relativity", "Relativity"],
  ["Researchers_in_geometric_algorithms", "Researchers in geometric algorithms"],
  ["Risk", "Risk"],
  ["Robust_statistics", "Robust statistics"],
  ["Rotational_symmetry", "Rotational symmetry"],
  ["Rubik%27s_Cube", "Rubik's Cube"],
  ["Russian_cryptographers", "Russian cryptographers"],
  ["Russian_logicians", "Russian logicians"],
  ["Russian_statisticians", "Russian statisticians"],
  ["Scaling_symmetries", "Scaling symmetries"],
  ["Scientific_organizations", "Scientific organizations"],
  ["Scottish_statisticians", "Scottish statisticians"],
  ["Search_engine_optimization", "Search engine optimization"],
  ["Second_Wranglers", "Second Wranglers"],
  ["Self-organization", "Self-organization"],
  ["Senior_Wranglers", "Senior Wranglers"],
  ["Serialism", "Serialism"],
  ["Set_theoretic_programming_languages", "Set theoretic programming languages"],
  ["Signal_processing_stubs", "Signal processing stubs"],
  ["Social_statistics", "Social statistics"],
  ["Sorting_algorithms", "Sorting algorithms"],
  ["Spanning_tree", "Spanning tree"],
  ["Spatial_analysis", "Spatial analysis"],
  ["Spinors", "Spinors"],
  ["Sports_records_and_statistics", "Sports records and statistics"],
  ["Square_One_Television", "Square One Television"],
  ["Statistical_approximations", "Statistical approximations"],
  ["Statistical_charts_and_diagrams", "Statistical charts and diagrams"],
  ["Statistical_classification", "Statistical classification"],
  ["Statistical_data_agreements", "Statistical data agreements"],
  ["Statistical_data_coding", "Statistical data coding"],
  ["Statistical_data_sets", "Statistical data sets"],
  ["Statistical_data_types", "Statistical data types"],
  ["Statistical_inference", "Statistical inference"],
  ["Statistical_mechanics", "Statistical mechanics"],
  ["Statistical_mechanics_theorems", "Statistical mechanics theorems"],
  ["Statistical_models", "Statistical models"],
  ["Statistical_natural_language_processing", "Statistical natural language processing"],
  ["Statistical_organizations", "Statistical organizations"],
  ["Statistical_outliers", "Statistical outliers"],
  ["Statistical_principles", "Statistical principles"],
  ["Statistical_programming_languages", "Statistical programming languages"],
  ["Statistical_ratios", "Statistical ratios"],
  ["Statistical_software", "Statistical software"],
  ["Statistician_stubs", "Statistician stubs"],
  ["Statisticians", "Statisticians"],
  ["Statisticians_by_nationality", "Statisticians by nationality"],
  ["Statistics_stubs", "Statistics stubs"],
  ["Statistics-related_lists", "Statistics-related lists"],
  ["Stellation_diagrams", "Stellation diagrams"],
  ["String_metrics", "String metrics"],
  ["Structural_analysis", "Structural analysis"],
  ["Sudoku", "Sudoku"],
  ["Supersymmetry", "Supersymmetry"],
  ["Supertasks", "Supertasks"],
  ["Survival_analysis", "Survival analysis"],
  ["Swedish_information_theorists", "Swedish information theorists"],
  ["Swedish_statisticians", "Swedish statisticians"],
  ["Swiss_statisticians", "Swiss statisticians"],
  ["Symmetry", "Symmetry"],
  ["TeX", "TeX"],
  ["Technical_drawing", "Technical drawing"],
  ["Telephone_numbers", "Telephone numbers"],
  ["Theorem_proving_software_systems", "Theorem proving software systems"],
  ["Theoretical_biology", "Theoretical biology"],
  ["Theoretical_computer_science", "Theoretical computer science"],
  ["Theoretical_physics", "Theoretical physics"],
  ["Theories_of_deduction", "Theories of deduction"],
  ["Theory_of_computation", "Theory of computation"],
  ["Thermodynamics", "Thermodynamics"],
  ["Thomas_Carlyle", "Thomas Carlyle"],
  ["Tiling_puzzles", "Tiling puzzles"],
  ["Time", "Time"],
  ["Time_series_analysis", "Time series analysis"],
  ["Term_logic", "Traditional logic"],
  ["Trees_(data_structures)", "Trees (data structures)"],
  ["Troff", "Troff"],
  ["Turing_machine", "Turing machine"],
  ["Type_theory", "Type theory"],
  ["Unified_Modeling_Language", "Unified Modeling Language"],
  ["Units_of_area", "Units of area"],
  ["Variables", "Variables"],
  ["Variational_formalism_of_general_relativity", "Variational formalism of general relativity"],
  ["Volume", "Volume"],
  ["Vortices", "Vortices"],
  ["Warp_drive_theory", "Warp drive theory"],
  ["Wave_mechanics", "Wave mechanics"],
  ["Waves", "Waves"],
  ["Z_notation", "Z notation"],
  ["Zero_(linguistics)", "Zero (linguistics)"]
];