daftarlinkmath = [

["https://www.calculator.net/mortgage-calculator.html","Mortgage Calculator"],["https://www.calculator.net/loan-calculator.html","Loan Calculator"],["https://www.calculator.net/auto-loan-calculator.html","Auto Loan Calculator"],["https://www.calculator.net/interest-calculator.html","Interest Calculator"],["https://www.calculator.net/payment-calculator.html","Payment Calculator"],["https://www.calculator.net/retirement-calculator.html","Retirement Calculator"],["https://www.calculator.net/amortization-calculator.html","Amortization Calculator"],["https://www.calculator.net/investment-calculator.html","Investment Calculator"],["https://www.calculator.net/currency-calculator.html","Currency Calculator"],["https://www.calculator.net/inflation-calculator.html","Inflation Calculator"],["https://www.calculator.net/finance-calculator.html","Finance Calculator"],["https://www.calculator.net/mortgage-payoff-calculator.html","Mortgage Payoff Calculator"],["https://www.calculator.net/tax-calculator.html","Income Tax Calculator"],["https://www.calculator.net/compound-interest-calculator.html","Compound Interest Calculator"],["https://www.calculator.net/salary-calculator.html","Salary Calculator"],["https://www.calculator.net/401k-calculator.html","401K Calculator"],["https://www.calculator.net/interest-rate-calculator.html","Interest Rate Calculator"],["https://www.calculator.net/sales-tax-calculator.html","Sales Tax Calculator"],["https://www.calculator.net/house-affordability-calculator.html","House Affordability Calculator"],["https://www.calculator.net/savings-calculator.html","Savings Calculator"],["https://www.calculator.net/rent-calculator.html","Rent Calculator"],["https://www.calculator.net/marriage-calculator.html","Marriage Tax Calculator"],["https://www.calculator.net/estate-tax-calculator.html","Estate Tax Calculator"],["https://www.calculator.net/pension-calculator.html","Pension Calculator"],["https://www.calculator.net/social-security-calculator.html","Social Security Calculator"],["https://www.calculator.net/annuity-calculator.html","Annuity Calculator"],["https://www.calculator.net/annuity-payout-calculator.html","Annuity Payout Calculator"],["https://www.calculator.net/credit-card-calculator.html","Credit Card Calculator"],["https://www.calculator.net/credit-card-payoff-calculator.html","Credit Cards Payoff Calculator"],["https://www.calculator.net/debt-payoff-calculator.html","Debt Payoff Calculator"],["https://www.calculator.net/debt-consolidation-calculator.html","Debt Consolidation Calculator"],["https://www.calculator.net/repayment-calculator.html","Repayment Calculator"],["https://www.calculator.net/student-loan-calculator.html","Student Loan Calculator"],["https://www.calculator.net/college-cost-calculator.html","College Cost Calculator"],["https://www.calculator.net/simple-interest-calculator.html","Simple Interest Calculator"],["https://www.calculator.net/cd-calculator.html","CD Calculator"],["https://www.calculator.net/roth-ira-calculator.html","Roth IRA Calculator"],["https://www.calculator.net/ira-calculator.html","IRA Calculator"],["https://www.calculator.net/rmd-calculator.html","RMD Calculator"],["https://www.calculator.net/vat-calculator.html","VAT Calculator"],["https://www.calculator.net/cash-back-or-low-interest-calculator.html","Cash Back or Low Interest Calculator"],["https://www.calculator.net/auto-lease-calculator.html","Auto Lease Calculator"],["https://www.calculator.net/depreciation-calculator.html","Depreciation Calculator"],["https://www.calculator.net/average-return-calculator.html","Average Return Calculator"],["https://www.calculator.net/margin-calculator.html","Margin Calculator"],["https://www.calculator.net/discount-calculator.html","Discount Calculator"],["https://www.calculator.net/business-loan-calculator.html","Business Loan Calculator"],["https://www.calculator.net/debt-ratio-calculator.html","Debt-to-Income Ratio Calculator"],["https://www.calculator.net/real-estate-calculator.html","Real Estate Calculator"],["https://www.calculator.net/take-home-pay-calculator.html","Take-Home-Paycheck Calculator"],["https://www.calculator.net/personal-loan-calculator.html","Personal Loan Calculator"],["https://www.calculator.net/lease-calculator.html","Lease Calculator"],["https://www.calculator.net/refinance-calculator.html","Refinance Calculator"],["https://www.calculator.net/budget-calculator.html","Budget Calculator"],["https://www.calculator.net/rental-property-calculator.html","Rental Property Calculator"],["https://www.calculator.net/roi-calculator.html","ROI Calculator"],["https://www.calculator.net/apr-calculator.html","APR Calculator"],["https://www.calculator.net/fha-loan-calculator.html","FHA Loan Calculator"],["https://www.calculator.net/va-mortgage-calculator.html","VA Mortgage Calculator"],["https://www.calculator.net/down-payment-calculator.html","Down Payment Calculator"],["https://www.calculator.net/rent-vs-buy-calculator.html","Rent vs. Buy Calculator"],["https://www.calculator.net/payback-period-calculator.html","Payback Period Calculator"],["https://www.calculator.net/present-value-calculator.html","Present Value Calculator"],["https://www.calculator.net/future-value-calculator.html","Future Value Calculator"],["https://www.calculator.net/commission-calculator.html","Commission Calculator"],["https://www.calculator.net/mortgage-calculator-uk.html","Mortgage Calculator UK"],["https://www.calculator.net/canadian-mortgage-calculator.html","Canadian Mortgage Calculator"],["https://www.calculator.net/mortgage-amortization-calculator.html","Mortgage Amortization Calculator"],["https://www.calculator.net/percent-off-calculator.html","Percent Off Calculator"],

["https://www.calculator.net/bmi-calculator.html","BMI Calculator"],["https://www.calculator.net/calorie-calculator.html","Calorie Calculator"],["https://www.calculator.net/body-fat-calculator.html","Body Fat Calculator"],["https://www.calculator.net/bmr-calculator.html","BMR Calculator"],["https://www.calculator.net/macro-calculator.html","Macro Calculator"],["https://www.calculator.net/ideal-weight-calculator.html","Ideal Weight Calculator"],["https://www.calculator.net/pregnancy-calculator.html","Pregnancy Calculator"],["https://www.calculator.net/pregnancy-weight-gain-calculator.html","Pregnancy Weight Gain Calculator"],["https://www.calculator.net/pregnancy-conception-calculator.html","Pregnancy Conception Calculator"],["https://www.calculator.net/due-date-calculator.html","Due Date Calculator"],["https://www.calculator.net/pace-calculator.html","Pace Calculator"],["https://www.calculator.net/army-body-fat-calculator.html","Army Body Fat Calculator"],["https://www.calculator.net/carbohydrate-calculator.html","Carbohydrate Calculator"],["https://www.calculator.net/lean-body-mass-calculator.html","Lean Body Mass Calculator"],["https://www.calculator.net/healthy-weight-calculator.html","Healthy Weight Calculator"],["https://www.calculator.net/calories-burned-calculator.html","Calories Burned Calculator"],["https://www.calculator.net/protein-calculator.html","Protein Calculator"],["https://www.calculator.net/fat-intake-calculator.html","Fat Intake Calculator"],["https://www.calculator.net/tdee-calculator.html","TDEE Calculator"],["https://www.calculator.net/ovulation-calculator.html","Ovulation Calculator"],["https://www.calculator.net/conception-calculator.html","Conception Calculator"],["https://www.calculator.net/period-calculator.html","Period Calculator"],["https://www.calculator.net/gfr-calculator.html","GFR Calculator"],["https://www.calculator.net/body-type-calculator.html","Body Type Calculator"],["https://www.calculator.net/body-surface-area-calculator.html","Body Surface Area Calculator"],["https://www.calculator.net/bac-calculator.html","BAC Calculator"],["https://www.calculator.net/anorexic-bmi-calculator.html","Anorexic BMI Calculator"],["https://www.calculator.net/weight-watchers-points-calculator.html","Weight Watcher Points Calculator"],["https://www.calculator.net/overweight-calculator.html","Overweight Calculator"],

["https://www.calculator.net/scientific-calculator.html","Scientific Calculator"],["https://www.calculator.net/fraction-calculator.html","Fraction Calculator"],["https://www.calculator.net/percent-calculator.html","Percentage Calculator"],["https://www.calculator.net/triangle-calculator.html","Triangle Calculator"],["https://www.calculator.net/volume-calculator.html","Volume Calculator"],["https://www.calculator.net/standard-deviation-calculator.html","Standard Deviation Calculator"],["https://www.calculator.net/random-number-generator.html","Random Number Generator"],["https://www.calculator.net/number-sequence-calculator.html","Number Sequence Calculator"],["https://www.calculator.net/percent-error-calculator.html","Percent Error Calculator"],["https://www.calculator.net/exponent-calculator.html","Exponent Calculator"],["https://www.calculator.net/binary-calculator.html","Binary Calculator"],["https://www.calculator.net/hex-calculator.html","Hex Calculator"],["https://www.calculator.net/half-life-calculator.html","Half-Life Calculator"],["https://www.calculator.net/quadratic-formula-calculator.html","Quadratic Formula Calculator"],["https://www.calculator.net/slope-calculator.html","Slope Calculator"],["https://www.calculator.net/log-calculator.html","Log Calculator"],["https://www.calculator.net/area-calculator.html","Area Calculator"],["https://www.calculator.net/sample-size-calculator.html","Sample Size Calculator"],["https://www.calculator.net/probability-calculator.html","Probability Calculator"],["https://www.calculator.net/statistics-calculator.html","Statistics Calculator"],["https://www.calculator.net/mean-median-mode-range-calculator.html","Mean, Median, Mode, Range Calculator"],["https://www.calculator.net/permutation-and-combination-calculator.html","Permutation and Combination Calculator"],["https://www.calculator.net/z-score-calculator.html","Z-score Calculator"],["https://www.calculator.net/confidence-interval-calculator.html","Confidence Interval Calculator"],["https://www.calculator.net/ratio-calculator.html","Ratio Calculator"],["https://www.calculator.net/distance-calculator.html","Distance Calculator"],["https://www.calculator.net/circle-calculator.html","Circle Calculator"],["https://www.calculator.net/surface-area-calculator.html","Surface Area Calculator"],["https://www.calculator.net/pythagorean-theorem-calculator.html","Pythagorean Theorem Calculator"],["https://www.calculator.net/right-triangle-calculator.html","Right Triangle Calculator"],["https://www.calculator.net/root-calculator.html","Root Calculator"],["https://www.calculator.net/lcm-calculator.html","Least Common Multiple Calculator"],["https://www.calculator.net/gcf-calculator.html","Greatest Common Factor Calculator"],["https://www.calculator.net/factor-calculator.html","Factor Calculator"],["https://www.calculator.net/rounding-calculator.html","Rounding Calculator"],["https://www.calculator.net/matrix-calculator.html","Matrix Calculator"],["https://www.calculator.net/scientific-notation-calculator.html","Scientific Notation Calculator"],["https://www.calculator.net/big-number-calculator.html","Big Number Calculator"],["https://www.calculator.net/prime-factorization-calculator.html","Prime Factorization Calculator"],["https://www.calculator.net/common-factor-calculator.html","Common Factor Calculator"],["https://www.calculator.net/basic-calculator.html","Basic Calculator"],["https://www.calculator.net/long-division-calculator.html","Long Division Calculator"],["https://www.calculator.net/average-calculator.html","Average Calculator"],["https://www.calculator.net/p-value-calculator.html","P-value Calculator"],

["https://www.calculator.net/age-calculator.html","Age Calculator"],["https://www.calculator.net/date-calculator.html","Date Calculator"],["https://www.calculator.net/time-calculator.html","Time Calculator"],["https://www.calculator.net/hours-calculator.html","Hours Calculator"],["https://www.calculator.net/gpa-calculator.html","GPA Calculator"],["https://www.calculator.net/grade-calculator.html","Grade Calculator"],["https://www.calculator.net/height-calculator.html","Height Calculator"],["https://www.calculator.net/concrete-calculator.html","Concrete Calculator"],["https://www.calculator.net/ip-subnet-calculator.html","IP Subnet Calculator"],["https://www.calculator.net/bra-size-calculator.html","Bra Size Calculator"],["https://www.calculator.net/password-generator.html","Password Generator"],["https://www.calculator.net/dice-roller.html","Dice Roller"],["https://www.calculator.net/conversion-calculator.html","Conversion Calculator"],["https://www.calculator.net/fuel-cost-calculator.html","Fuel Cost Calculator"],["https://www.calculator.net/voltage-drop-calculator.html","Voltage Drop Calculator"],["https://www.calculator.net/btu-calculator.html","BTU Calculator"],["https://www.calculator.net/square-footage-calculator.html","Square Footage Calculator"],["https://www.calculator.net/time-card-calculator.html","Time Card Calculator"],["https://www.calculator.net/time-zone-calculator.html","Time Zone Calculator"],["https://www.calculator.net/love-calculator.html","Love Calculator"],["https://www.calculator.net/gdp-calculator.html","GDP Calculator"],["https://www.calculator.net/gas-mileage-calculator.html","Gas Mileage Calculator"],["https://www.calculator.net/horsepower-calculator.html","Horsepower Calculator"],["https://www.calculator.net/engine-horsepower-calculator.html","Engine Horsepower Calculator"],["https://www.calculator.net/stair-calculator.html","Stair Calculator"],["https://www.calculator.net/resistor-calculator.html","Resistor Calculator"],["https://www.calculator.net/ohms-law-calculator.html","Ohms Law Calculator"],["https://www.calculator.net/electricity-calculator.html","Electricity Calculator"],["https://www.calculator.net/tip-calculator.html","Tip Calculator"],["https://www.calculator.net/mileage-calculator.html","Mileage Calculator"],["https://www.calculator.net/density-calculator.html","Density Calculator"],["https://www.calculator.net/mass-calculator.html","Mass Calculator"],["https://www.calculator.net/weight-calculator.html","Weight Calculator"],["https://www.calculator.net/golf-handicap-calculator.html","Golf Handicap Calculator"],["https://www.calculator.net/sleep-calculator.html","Sleep Calculator"],["https://www.calculator.net/tire-size-calculator.html","Tire Size Calculator"],["https://www.calculator.net/roofing-calculator.html","Roofing Calculator"],["https://www.calculator.net/tile-calculator.html","Tile Calculator"],["https://www.calculator.net/mulch-calculator.html","Mulch Calculator"],["https://www.calculator.net/gravel-calculator.html","Gravel Calculator"],["https://www.calculator.net/wind-chill-calculator.html","Wind Chill Calculator"],["https://www.calculator.net/heat-index-calculator.html","Heat Index Calculator"],["https://www.calculator.net/dew-point-calculator.html","Dew Point Calculator"],["https://www.calculator.net/bandwidth-calculator.html","Bandwidth Calculator"],["https://www.calculator.net/time-duration-calculator.html","Time Duration Calculator"],["https://www.calculator.net/day-counter.html","Day Counter"],["https://www.calculator.net/day-of-the-week-calculator.html","Day of the Week Calculator"],

["https://www.overleaf.com/","Overleaf, Online LaTeX Editor"],
["https://www.desmos.com/calculator","Graphing Calculator"],
["https://www.desmos.com/scientific","Scientific Calculator"],
["https://www.desmos.com/fourfunction","4-Function Calculator"],
["https://www.desmos.com/practice","Desmos Test Practice"],
["https://www.desmos.com/matrix","Matrix Calculator"],
["https://www.desmos.com/geometry","Geometry Tool"],
["https://www.desmos.com/3d","3D Graphing Calculator"],
["https://www.symbolab.com/graphing-calculator","Graphing Calculator"],
["https://www.symbolab.com/calculator/math/binary","Binary Calculator"],
["https://www.symbolab.com/calculator/math/hex","Hex Calculator"],
["https://www.symbolab.com/calculator/math/log-base2","Log Base 2 Calculator"],
["https://www.symbolab.com/calculator/math/log","Log Calculator"],
["https://www.symbolab.com/calculator/math/percentage-find-percent","Percent Given Value Calculator"],
["https://www.symbolab.com/calculator/math/percentage","Percentage Calculator"],
["https://www.symbolab.com/calculator/math/percentage-error","Percentage Error Calculator"],
["https://www.symbolab.com/calculator/math/percentage-find-total-value","Value Given Percent Calculator"],
["https://www.symbolab.com/calculator/geometry/area","Area Calculator"],
["https://www.symbolab.com/calculator/geometry/circle","Circle Calculator"],
["https://www.symbolab.com/calculator/geometry/pythagorean-theorem","Pythagorean Theorem Calculator"],
["https://www.symbolab.com/calculator/geometry/surface","Surface Calculator"],
["https://www.symbolab.com/calculator/geometry/volume","Volume Calculator"],
["https://www.symbolab.com/calculator/personal_finance/amortization","Amortization Calculator"],
["https://www.symbolab.com/calculator/personal_finance/auto-loan","Auto Loan Calculator"],
["https://www.symbolab.com/calculator/personal_finance/compound_interest","Compound Interest Calculator"],
["https://www.symbolab.com/calculator/personal_finance/finance_charge","Finance Charge Calculator"],
["https://www.symbolab.com/calculator/personal_finance/inflation","Inflation Calculator"],
["https://www.symbolab.com/calculator/personal_finance/interest","Interest Calculator"],
["https://www.symbolab.com/calculator/personal_finance/investment","Investment Calculator"],
["https://www.symbolab.com/calculator/personal_finance/loan","Loan Calculator"],
["https://www.symbolab.com/calculator/personal_finance/mortgage","Mortgage Calculator"],
["https://www.symbolab.com/calculator/personal_finance/salary","Salary Calculator"],
["https://www.symbolab.com/calculator/personal_finance/salary-to-hourly","Salary to Hourly Calculator"],
["https://www.symbolab.com/calculator/personal_finance/sales-tax","Sales Tax Calculator"],
["https://www.symbolab.com/calculator/physics/acceleration","Acceleration Calculator"],
["https://www.symbolab.com/calculator/physics/angular-resolution","Angular Resolution Calculator"],
["https://www.symbolab.com/calculator/physics/angular-velocity","Angular Velocity Calculator"],
["https://www.symbolab.com/calculator/physics/aperture-area","Aperture Area Calculator"],
["https://www.symbolab.com/calculator/physics/bernoulli","Bernoulli Equation Calculator"],
["https://www.symbolab.com/calculator/physics/brewster-angle","Brewster's Angle Calculator"],
["https://www.symbolab.com/calculator/physics/buoyancy","Buoyancy Calculator"],
["https://www.symbolab.com/calculator/physics/flow-rate","Cylindrical Pipe Flow Rate Calculator"],
["https://www.symbolab.com/calculator/physics/density","Density Calculator"],
["https://www.symbolab.com/calculator/physics/displacement","Displacement (distance traveled) Calculator"],
["https://www.symbolab.com/calculator/physics/drag-equation","Drag Equation"],
["https://www.symbolab.com/calculator/physics/emc","E = mc<sup>2</sup> Calculator"],
["https://www.symbolab.com/calculator/physics/force","Force Calculator"],
["https://www.symbolab.com/calculator/physics/free-fall","Free Fall Calculator"],
["https://www.symbolab.com/calculator/physics/friction","Friction Calculator"],
["https://www.symbolab.com/calculator/physics/froude-number","Froude Number Calculator"],
["https://www.symbolab.com/calculator/physics/gravitational-force","Gravitational Force Calculator"],
["https://www.symbolab.com/calculator/physics/hydraulic-pressure","Hydraulic Pressure Calculator"],
["https://www.symbolab.com/calculator/physics/hydraulic-radius","Hydraulic Radius Calculator (Full Pipe)"],
["https://www.symbolab.com/calculator/physics/hydrostatic-pressure","Hydrostatic Pressure Calculator"],
["https://www.symbolab.com/calculator/physics/impulse-and-momentum","Impulse and Momentum Calculator"],
["https://www.symbolab.com/calculator/physics/index-of-refraction","index of Refraction Calculator"],
["https://www.symbolab.com/calculator/physics/kinetic-energy","Kinetic Energy Calculator"],
["https://www.symbolab.com/calculator/physics/knudsen-number","Knudsen Number Calculator"],
["https://www.symbolab.com/calculator/physics/length-contraction","Length Contraction Calculator"],
["https://www.symbolab.com/calculator/physics/lightning-distance","Lightning Distance Calculator"],
["https://www.symbolab.com/calculator/physics/mach-number","Mach Number Calculator"],
["https://www.symbolab.com/calculator/physics/magnitude-of-acceleration","Magnitude of Acceleration Calculator"],
["https://www.symbolab.com/calculator/physics/malus-law","Malus Law Calculator"],
["https://www.symbolab.com/calculator/physics/moment-of-inertia","Moment of Inertia Calculator"],
["https://www.symbolab.com/calculator/physics/newtons-second-law","Newton's Second Law Calculator"],
["https://www.symbolab.com/calculator/physics/normal-force","Normal Force Calculator"],
["https://www.symbolab.com/calculator/physics/period-of-pendulum","Period Pendulum Calculator"],
["https://www.symbolab.com/calculator/physics/poisson-ratio","Poisson's Ratio Calculator"],
["https://www.symbolab.com/calculator/physics/potential-energy","Potential Energy Calculator"],
["https://www.symbolab.com/calculator/physics/pressure","Pressure Calculator"],
["https://www.symbolab.com/calculator/physics/reduced-mass","Reduced Mass Calculator"],
["https://www.symbolab.com/calculator/physics/rotational-kinetic-energy","Rational Kinetic Energy Calculator"],
["https://www.symbolab.com/calculator/physics/strain","Strain Calculator"],
["https://www.symbolab.com/calculator/physics/stress","Stress Calculator"],
["https://www.symbolab.com/calculator/physics/velocity-distance-covered","Velocity Calculator"],
["https://www.symbolab.com/calculator/physics/work","Work Calculator"],
["https://www.symbolab.com/calculator/conversion/area","Area Converter"],
["https://www.symbolab.com/calculator/conversion/base","Base Converter"],
["https://www.symbolab.com/calculator/conversion/download-speed","Download Speed Converter"],
["https://www.symbolab.com/calculator/conversion/length","Length Converter"],
["https://www.symbolab.com/calculator/conversion/megabytes","Megabytes Converter"],
["https://www.symbolab.com/calculator/conversion/power","Power Converter"],
["https://www.symbolab.com/calculator/conversion/pressure-convertor","Pressure Converter"],
["https://www.symbolab.com/calculator/conversion/roman_numeral","Roman Numerals Converter"],
["https://www.symbolab.com/calculator/conversion/temperature","Temperature Converter"],
["https://www.symbolab.com/calculator/conversion/time","Time Converter"],
["https://www.symbolab.com/calculator/conversion/velocity","Velocity Converter"],
["https://www.symbolab.com/calculator/conversion/volume","Volume Converter"],
["https://www.symbolab.com/calculator/conversion/weight","Weight Converter"],
["https://www.symbolab.com/calculator/time-date/24-hours","24-Hours Clock Calculator"],
["https://www.symbolab.com/calculator/time-date/age","Age Calculator"],
["https://www.symbolab.com/calculator/time-date/date","Date Calculator"],
["https://www.symbolab.com/calculator/time-date/hours","Hours Calculator"],
["https://www.symbolab.com/calculator/time-date/time-calculator","Time Calculator"],
["https://www.symbolab.com/calculator/cooking/cooking-measurement","Cooking Measurement Converter"],
["https://www.symbolab.com/calculator/cooking/cooking-ingredient","Cooking Ingredient Converter"],
["https://www.symbolab.com/calculator/cooking/cake-pan","Cake Pan Converter"],
["https://www.symbolab.com/calculator/fitness/bmi","BMI Calculator"],
["https://www.symbolab.com/calculator/fitness/bmr","BMR Calculator"],
["https://www.symbolab.com/calculator/fitness/body-fat","Body Fat Calculator"],
["https://www.symbolab.com/calculator/fitness/calorie","Calorie Calculator"],
["https://www.symbolab.com/calculator/fitness/calories-burned","Calories Burned Calculator"],
["https://www.symbolab.com/calculator/fitness/lean-body-mass","Lean Body Mass Calculator"],
["https://www.symbolab.com/calculator/fitness/pace","Pace Calculator"],
["https://www.symbolab.com/calculator/chemistry/atom2","Atom Calculator (neutrons)"],
["https://www.symbolab.com/calculator/chemistry/atom1","Atom Calculator (protons)"],
["https://www.symbolab.com/calculator/chemistry/mole","Mole Calculator"],
["https://www.symbolab.com/calculator/construction/circle_footage_cost_calculator","Circle Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/concrete_ark_volume","Concrete Ark Volume Calculator"],
["https://www.symbolab.com/calculator/construction/concrete_round_slab","Concrete Round Slab Volume Calculator"],
["https://www.symbolab.com/calculator/construction/concrete_steps","Concrete Steps Calculator"],
["https://www.symbolab.com/calculator/construction/concrete_volume","Concrete Volume Calculator"],
["https://www.symbolab.com/calculator/construction/decagon_footage_cost_calculator","Decagon Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/feet_inches_calculator","Feet and Inches Calculator"],
["https://www.symbolab.com/calculator/construction/footage_cost_calculator","Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/heptagon_footage_cost_calculator","Heptagon Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/hexagon_footage_cost_calculator","Hexagon Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/meters_centimeters_calculator","Meters and Centimeters Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_annulus","Mulch Annulus Calculator"],
["https://www.symbolab.com/calculator/construction/mulch","Mulch Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_circle_border","Mulch Circle Border Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_circle_volume","Mulch Circle Volume Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_rectangle_border","Mulch Rectangle Border Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_rectangle","Mulch Rectangle Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_square","Mulch Square Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_trapezoid","Mulch Trapezoid Calculator"],
["https://www.symbolab.com/calculator/construction/mulch_triangle","Mulch Triangle Calculator"],
["https://www.symbolab.com/calculator/construction/octagon_footage_cost_calculator","Octagon Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/pentagon_footage_cost_calculator","Pentagon Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/rectangle_footage_cost_calculator","Rectangle Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/square_footage_cost_calculator","Square Footage Cost Calculator"],
["https://www.symbolab.com/calculator/construction/triangle_footage_cost_calculator","Triangle Footage Cost Calculator"],
["https://www.symbolab.com/calculator/finance/apy","APY Calculator"],
["https://www.symbolab.com/calculator/finance/cash_flow","Cash Flow to Debt Ratio Calculator"],
["https://www.symbolab.com/calculator/finance/cash_ratio","Cash Ratio Calculator"],
["https://www.symbolab.com/calculator/finance/cd_calculator","Certificate of Deposit Calculator"],
["https://www.symbolab.com/calculator/finance/cagr","Compound Annual Growth Rate Calculator"],
["https://www.symbolab.com/calculator/finance/compound_interest_rate","Compound Interest Rate Calculator"],
["https://www.symbolab.com/calculator/finance/current_ratio","Current Ratio Calculator"],
["https://www.symbolab.com/calculator/finance/dividend","Dividend Calculator"],
["https://www.symbolab.com/calculator/finance/dividend_discount_model","Dividend Discount Model Calculator"],
["https://www.symbolab.com/calculator/finance/dividend_payout_ratio","Dividend Payout Ratio Calculator"],
["https://www.symbolab.com/calculator/finance/ebitda","EBITDA Calculator"],
["https://www.symbolab.com/calculator/finance/earning_share","Earnings per Share Calculator"],
["https://www.symbolab.com/calculator/finance/effective_interest_rate","Effective Interest Rate Calculator"],
["https://www.symbolab.com/calculator/finance/ear","Equivalent Rate (EAR) Calculator"],
["https://www.symbolab.com/calculator/finance/expense_ratio_calc","Expense Ratio Calculator"],
["https://www.symbolab.com/calculator/finance/expense_ratio_calc_cost","Expense Ratio Calculator (Cost of ETF)"],
["https://www.symbolab.com/calculator/finance/forward_rate","Forward Rate Calculator"],
["https://www.symbolab.com/calculator/finance/future-value","Future Value Calculator"],
["https://www.symbolab.com/calculator/finance/investment_calculator","Investment Calculator"],
["https://www.symbolab.com/calculator/finance/net_profit_margin","Net Profit Margin Calculator"],
["https://www.symbolab.com/calculator/finance/ROAS_calculator","Return On Ad Spend (ROAS) Calculator"],
["https://www.symbolab.com/calculator/sales/discount","Discount Calculator"],
["https://www.symbolab.com/calculator/sales/layaway_plan","Layaway Plan Calculator"],
["https://www.symbolab.com/calculator/sales/margin","Margin Calculator"],
["https://www.symbolab.com/calculator/sales/profit_margin","Profit Margin Calculator"],
["https://www.symbolab.com/calculator/sales/selling_price","Selling Price Calculator"],
["https://www.symbolab.com/calculator/sales/tip","Tip Calculator"],
["https://www.symbolab.com/calculator/sales/total-price","Total Price Calculator"],
["https://www.symbolab.com/calculator/statistics/statistics","Statistics Calculator"],
["https://www.symbolab.com/calculator/statistics/p-value","P-value Calculator"],
["https://www.symbolab.com/calculator/statistics/standard-deviation","Standard Deviation Calculator"],
["https://www.symbolab.com/calculator/other/dice-roller","Dice Roller"],
["https://www.symbolab.com/calculator/other/download-time","Download Time Calculator"],
["https://www.symbolab.com/calculator/other/gpa-planning","GPA Planning Calculator"],
["https://www.symbolab.com/calculator/other/grade","Grade Calculator"],
["https://www.symbolab.com/calculator/other/height","Height Calculator"],
["https://www.symbolab.com/calculator/other/prime-number","Prime Number Calculator"],
["https://www.symbolab.com/calculator/other/random-number-generator","Random Number Generator"],
["https://www.symbolab.com/geometry-calculator","Geometry Calculator"],
["https://www.symbolab.com/cheat-sheets/Algebra","Algebra Cheat Sheet"],
["https://www.symbolab.com/cheat-sheets/Trigonometry","Trigonometry Cheat Sheet"],
["https://www.symbolab.com/cheat-sheets/Limits","Limit Cheat Sheet"],
["https://www.symbolab.com/cheat-sheets/Derivatives","Derivatives Cheat Sheet"],
["https://www.symbolab.com/cheat-sheets/Integrals","Integral Cheat Sheet"],
["https://www.symbolab.com/solver","Step-by-Step Calculator"],

["https://www.calculatorsoup.com/calculators/math/prime-numbers.php","1000 Prime Numbers"],
["https://www.calculatorsoup.com/calculators/algebra/absolute-difference-calculator.php","Absolute Difference Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/absolute-value-calculator.php","Absolute Value Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/acceleration.php","Acceleration Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/acres-to-square-feet.php","Acres to Square Feet"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-activity.php","Activity Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/math/adding-fractions-calculator.php","Adding and Subtracting Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/math/adding-and-subtracting-integers-calculator.php","Adding and Subtracting Integers"],
["https://www.calculatorsoup.com/calculators/financial/adding-machine-calculator.php","Adding Machine Calculator"],
["https://www.calculatorsoup.com/calculators/financial/loan-calculator-advanced.php","Advanced Loan Calculator"],
["https://www.calculatorsoup.com/calculators/time/age-calculator.php","Age Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/","Algebra Calculators"],
["https://www.calculatorsoup.com/calculators/wordproblems/algebrawordproblem2.php","Algebra Word Problems: Age"],
["https://www.calculatorsoup.com/calculators/wordproblems/algebrawordproblem1.php","Algebra Word Problems: Coins"],
["https://www.calculatorsoup.com/calculators/financial/amortization-schedule-calculator.php","Amortization Schedule Calculator"],
["https://www.calculatorsoup.com/calculators/financial/amortization-equal-principal-payments-calculator.php","Amortization Schedule Calculator: Equal Principal Payments"],
["https://www.calculatorsoup.com/calculators/conversions/angle.php","Angle Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/financial/annuity-table.php","Annuity on Loan : Table Creator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/annulus.php","Annulus Calculator"],
["https://www.calculatorsoup.com/calculators/financial/apr-calculator.php","APR Calculator"],
["https://www.calculatorsoup.com/calculators/financial/apr-calculator-basic.php","APR Calculator Basic"],
["https://www.calculatorsoup.com/calculators/conversions/area.php","Area Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/average.php","Average Calculator (Mean)"],
["https://www.calculatorsoup.com/calculators/physics/velocity_avg.php","Average Velocity Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/weightavoirdupois.php","Avoirdupois Weight Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/math/basic.php","Basic Calculator"],
["https://www.calculatorsoup.com/calculators/financial/bid-ask-calculator.php","Bid-Ask Calculator"],
["https://www.calculatorsoup.com/calculators/health/bmi-calculator.php","BMI Calculator (Body Mass Index)"],
["https://www.calculatorsoup.com/calculators/health/bmi-calculator-women.php","BMI Calculator for Women"],
["https://www.calculatorsoup.com/calculators/games/bingo-number-generator.php","Bingo Number Generator"],
["https://www.calculatorsoup.com/calculators/games/bingo-card-generator.php","Bingo Card Generator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/capsule.php","Capsule Calculator"],
["https://www.calculatorsoup.com/calculators/financial/car-loan-calculator.php","Car Loan Calculator"],
["https://www.calculatorsoup.com/calculators/financial/car-loan-payment-calculator.php","Car Loan Payment Calculator"],
["https://www.calculatorsoup.com/calculators/financial/cd-calculator.php","CD Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/celsius-to-fahrenheit.php","Celsius to Fahrenheit | °C to °F"],
["https://www.calculatorsoup.com/calculators/conversions/celsius-to-kelvin.php","Celsius to Kelvin | °C to K"],
["https://www.calculatorsoup.com/calculators/conversions/celsius-to-rankine.php","Celsius to Rankine | °C to °R"],
["https://www.calculatorsoup.com/calculators/conversions/cm-to-inches.php","Centimeters to Inches | cm to in"],
["https://www.calculatorsoup.com/calculators/statistics/character-counter.php","Character Counter"],
["https://www.calculatorsoup.com/calculators/financial/checkbook-balance-calculator.php","Checkbook Balance Calculator"],
["https://www.calculatorsoup.com/calculators/financial/checkbook-calculator.php","Checkbook Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/numberstowords.php","Check Writing (Numbers to Words)"],
["https://www.calculatorsoup.com/calculators/chemistry/","Chemistry Calculators"],
["https://www.calculatorsoup.com/calculators/geometry-plane/circle.php","Circle Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/cylinder.php","Circular Cylinder Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/permutationscircular.php","Circular Permutation Calculator (Pn)"],
["https://www.calculatorsoup.com/calculators/statistics/coin-flipper.php","Coin Flipper"],
["https://www.calculatorsoup.com/calculators/discretemathematics/combinationsreplacement.php","Combination with Replacement Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/combinations.php","Combinations Calculator (nCr)"],
["https://www.calculatorsoup.com/calculators/math/commonfactors.php","Common Factor Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionscomparing.php","Comparing Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/completing-the-square-calculator.php","Completing the Square Calculator"],
["https://www.calculatorsoup.com/calculators/financial/compound-interest-calculator.php","Compound Interest Calculator"],
["https://www.calculatorsoup.com/calculators/math/complex-fraction-calculator.php","Complex Fraction Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/computerstorage.php","Computer Storage Units Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/construction/concrete-calculator.php","Concrete Volume Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/cone.php","Cone Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/conicalfrustum.php","Conical Frustrum Calculator"],
["https://www.calculatorsoup.com/calculators/construction/","Construction Calculators"],
["https://www.calculatorsoup.com/calculators/conversions/","Conversion Calculators"],
["https://www.calculatorsoup.com/calculators/conversions/cooking.php","Cooking Conversion Calculators"],
["https://www.calculatorsoup.com/calculators/geometry-solids/cube.php","Cube Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/cube-calculator.php","Cube Calculator x³"],
["https://www.calculatorsoup.com/calculators/algebra/cuberoots.php","Cube Root Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/cubicequation.php","Cubic Equation Calculator - 3rd Order Polynomial"],
["https://www.calculatorsoup.com/calculators/construction/cubic-yards-calculator.php","Cubic Yards Calculator"],
["https://www.calculatorsoup.com/calculators/financial/currency-appreciation-depreciation-calculator.php","Currency Appreciation and Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/financial/currency-converter.php","Currency Converter"],
["https://www.calculatorsoup.com/calculators/time/date-day.php","Date Days Calculator"],
["https://www.calculatorsoup.com/calculators/time/date-difference-calculator.php","Date Difference Calculator"],
["https://www.calculatorsoup.com/calculators/time/date-calendar.php","Date ± Calendar Units Calculator"],
["https://www.calculatorsoup.com/calculators/financial/debt-ratios-calculator.php","Debt Ratios Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/convert-decimal-degrees-to-degrees-minutes-seconds.php","Decimal Degrees to Degrees Minutes Seconds"],
["https://www.calculatorsoup.com/calculators/math/decimal-to-fraction-calculator.php","Decimal to Fraction Calculator"],
["https://www.calculatorsoup.com/calculators/math/decimal-to-percent-calculator.php","Decimal to Percent Calculator"],
["https://www.calculatorsoup.com/calculators/time/decimal-to-time-calculator.php","Decimal to Time Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-declining-balance.php","Declining Balance Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/financial/deferred-fixed-annuity-calculator.php","Deferred Fixed Annuity Calculator"],
["https://www.calculatorsoup.com/calculators/physics/density.php","Density (Physics)"],
["https://www.calculatorsoup.com/calculators/conversions/density.php","Density Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-calculator.php","Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-depreciation-calculators.php","Depreciation Calculators Index"],
["https://www.calculatorsoup.com/calculators/statistics/descriptivestatistics.php","Descriptive Statistics Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/square-feet-to-acres.php","Square Feet to Acres"],
["https://www.calculatorsoup.com/calculators/conversions/square-feet-to-square-meters.php","Square Feet to Square Meters"],
["https://www.calculatorsoup.com/calculators/conversions/square-meters-to-square-feet.php","Square Meters to Square Feet"],
["https://www.calculatorsoup.com/calculators/statistics/statistics-formulas.php","Statistics Formulas"],
["https://www.calculatorsoup.com/calculators/math/diamond-problem-solver.php","Diamond Problem Solver"],
["https://www.calculatorsoup.com/calculators/games/diceroll.php","Dice Roller"],
["https://www.calculatorsoup.com/calculators/algebra/difference-of-two-squares-calculator.php","Difference of Two Squares Calculator"],
["https://www.calculatorsoup.com/calculators/time/stopwatchtimer.php","Digital Stopwatch Timer Calculator"],
["https://www.calculatorsoup.com/calculators/financial/discount-calculator.php","Discount Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/","Discrete Mathematics Calculators"],
["https://www.calculatorsoup.com/calculators/physics/displacement-calculator-svt.php","Displacement as a Function of Average Velocity and Time"],
["https://www.calculatorsoup.com/calculators/physics/displacement_v_t.php","Displacement as a Function of Velocity and Time"],
["https://www.calculatorsoup.com/calculators/physics/displacement_v_a_t.php","Displacement as a Function of Velocity, Acceleration and Time"],
["https://www.calculatorsoup.com/calculators/geometry-plane/distance-two-points.php","Distance Calculator 2D"],
["https://www.calculatorsoup.com/calculators/geometry-solids/distance-two-points.php","Distance Calculator 3D"],
["https://www.calculatorsoup.com/calculators/conversions/distance.php","Distance Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/dot-product-calculator.php","Dot Product Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-declining-double.php","Double Declining Balance Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/physics/emc2.php","E = mc<sup>2</sup>&nbsp;&nbsp;Calculator"],
["https://www.calculatorsoup.com/calculators/financial/effective-interest-rate-calculator.php","Effective Interest Rate Calculator"],
["https://www.calculatorsoup.com/calculators/financial/effective-annual-rate-calculator.php","Effective Annual Rate (EAR) Calculator"],
["https://www.calculatorsoup.com/calculators/physics/elastic-potential.php","Elastic Potential Energy Calculator"],
["https://www.calculatorsoup.com/calculators/financial/emi-loan-calculator.php","EMI Loan Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/energy.php","Energy Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/triangles-equilateral.php","Equilateral Triangles Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionsequivalent.php","Equivalent Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/financial/equivalent-interest-rate-calculator.php","Equivalent Interest Rate Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionsestimating.php","Estimating Sums and Differences of Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/math/gcf-euclids-algorithm.php","Euclid's Algorithm Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/evenpermutations.php","Even Permutations Calculator"],
["https://www.calculatorsoup.com/calculators/math/expanded-form-calculator.php","Expanded Form Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/exponent.php","Exponents Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/large-exponent-calculator.php","Large Exponents Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/factorials.php","Factorial Calculator n!"],
["https://www.calculatorsoup.com/calculators/math/factors.php","Factorization Calculator"],
["https://www.calculatorsoup.com/calculators/financial/tax-federal-est.php","Federal Income Tax Estimator"],
["https://www.calculatorsoup.com/calculators/construction/feetandinches.php","Feet and Inches Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/fahrenheit-to-celsius.php","Fahrenheit to Celsius | °F to °C"],
["https://www.calculatorsoup.com/calculators/conversions/fahrenheit-to-kelvin.php","Fahrenheit to Kelvin | °F to K"],
["https://www.calculatorsoup.com/calculators/conversions/fahrenheit-to-rankine.php","Fahrenheit to Rankine | °F to °R"],
["https://www.calculatorsoup.com/calculators/discretemathematics/fibonacci-calculator.php","Fibonacci Numbers Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/fifthroots.php","Fifth Roots Calculator"],
["https://www.calculatorsoup.com/calculators/financial/","Financial Calculators"],
["https://www.calculatorsoup.com/calculators/financial/website-financial-calculators.php","Financial Calculator Widgets"],
["https://www.calculatorsoup.com/calculators/financial/index-financial-ratio-calculators.php","Financial Ratio Calculators"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-fixed-declining-balance.php","Fixed Declining Balance Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/physics/force.php","Force Calculator (Physics)"],
["https://www.calculatorsoup.com/calculators/conversions/force.php","Force Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/fourthroots.php","Fourth Roots Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/exponent-fractions.php","Fraction Exponents Calculator"],
["https://www.calculatorsoup.com/calculators/math/fraction-to-decimal-calculator.php","Fraction to Decimal Calculator"],
["https://www.calculatorsoup.com/calculators/math/fraction-to-percent-calculator.php","Fraction to Percent Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractions.php","Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionscalculators.php","Fractions Calculators"],
["https://www.calculatorsoup.com/calculators/math/fractions-average.php","Fractions Averaging"],
["https://www.calculatorsoup.com/calculators/math/fractionsnumberline.php","Fractions Number Line/ Chart"],
["https://www.calculatorsoup.com/calculators/math/fractionssolvex.php","Fractions Solve for Unknown"],
["https://www.calculatorsoup.com/calculators/math/fractionstable.php","Fractions Table"],
["https://www.calculatorsoup.com/calculators/physics/friction.php","Friction Calculator"],
["https://www.calculatorsoup.com/calculators/financial/future-value-calculator-basic.php","Future Value Calculator (simple)"],
["https://www.calculatorsoup.com/calculators/financial/future-value-calculator.php","Future Value Calculator (comprehensive)"],
["https://www.calculatorsoup.com/calculators/financial/future-value-table-1.php","Future Value of $1 Table (FVIF)"],
["https://www.calculatorsoup.com/calculators/financial/future-value-table-annuity.php","Future Value of $1 Annuity Table (FVIFA)"],
["https://www.calculatorsoup.com/calculators/financial/future-value-investment-account-calculator.php","Future Value of an Investment Calculator"],
["https://www.calculatorsoup.com/calculators/financial/future-value-investment-calculator.php","Future Value of a Present Sum"],
["https://www.calculatorsoup.com/calculators/financial/future-value-annuity-calculator.php","Future Value of Annuity Calculator"],
["https://www.calculatorsoup.com/calculators/financial/future-value-cash-flows-calculator.php","Future Value of Cash Flows Calculator"],
["https://www.calculatorsoup.com/calculators/games/","Games and Sports Calculators"],
["https://www.calculatorsoup.com/calculators/tools/gas-mileage-calculator.php","Gas Mileage Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/geometricshapes.php","Geometric Shapes and Formulas in Solid Geometry"],
["https://www.calculatorsoup.com/calculators/geometry-plane/geometricshapes.php","Geometric Shapes in Plane Geometry"],
["https://www.calculatorsoup.com/calculators/geometry-calculators.php","Geometry Calculators"],
["https://www.calculatorsoup.com/calculators/math/goldenratio.php","Golden Ratio Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/gpa-calculator.php","GPA Calculator"],
["https://www.calculatorsoup.com/calculators/physics/gravitational-potential.php","Gravitational Potential Energy Calculator"],
["https://www.calculatorsoup.com/calculators/math/gcf.php","Greatest Common Factor Calculator"],
["https://www.calculatorsoup.com/calculators/financial/gross-pay-calculator.php","Gross Pay Calculator"],
["https://www.calculatorsoup.com/calculators/health/index.php","Health Calculators"],
["https://www.calculatorsoup.com/calculators/conversions/heightftcm.php","Height Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/height-ft-and-in-to-cm.php","Height ft &amp; in to cm"],
["https://www.calculatorsoup.com/calculators/conversions/height-cm-to-in-and-ft.php","Height Converter cm to in &amp; ft"],
["https://www.calculatorsoup.com/calculators/conversions/hours-to-minutes.php","Hours to Minutes Coverter"],
["https://www.calculatorsoup.com/calculators/geometry-solids/hemisphere.php","Hemisphere Calculator"],
["https://www.calculatorsoup.com/calculators/physics/hookes-law.php","Hooke's Law Calculator"],
["https://www.calculatorsoup.com/calculators/time/hours.php","Hours Calculator"],
["https://www.calculatorsoup.com/calculators/financial/how-much-car-can-i-afford.php","How Much Car can I Afford?"],
["https://www.calculatorsoup.com/calculators/financial/how-much-house-can-i-afford.php","How Much House can I Afford?"],
["https://www.calculatorsoup.com/calculators/financial/how-much-loan-can-i-afford.php","How Much of a Loan can I Afford?"],
["https://www.calculatorsoup.com/calculators/physics/ideal-gas-law.php","Ideal Gas Law Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionssimplify.php","Improper Fractions to Mixed Numbers"],
["https://www.calculatorsoup.com/calculators/physics/impulse.php","Impulse Calculator"],
["https://www.calculatorsoup.com/calculators/physics/impulse-momentum.php","Impulse-Momentum Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/inches-to-cm.php","Inches to Centimeters | in to cm"],
["https://www.calculatorsoup.com/calculators/financial/inflation-calculator.php","Inflation Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-interest-apr-calculators.php","Interest and APR Calculators"],
["https://www.calculatorsoup.com/calculators/financial/interest-only-mortgage-calculator.php","Interest Only Mortgage Calculator"],
["https://www.calculatorsoup.com/calculators/financial/interest-rate-table.php","Interest Rate on Table Creator"],
["https://www.calculatorsoup.com/calculators/trigonometry/graphs-inversefunctions.php","Inverse Trigonometric Function Graphs"],
["https://www.calculatorsoup.com/calculators/trigonometry/inversetrigonometricfunctions.php","Inverse Trigonometric Functions"],
["https://www.calculatorsoup.com/calculators/financial/future-value-investment-account-calculator.php","Investment Account Calculator"],
["https://www.calculatorsoup.com/calculators/financial/investment-calculator.php","Investment Calculator"],
["https://www.calculatorsoup.com/calculators/financial/investment-inflation-calculator.php","Investment Inflation Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/triangles-isosceles.php","Isosceles Triangles Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/kelvin-to-celsius.php","Kelvin to Celsius | K to °C"],
["https://www.calculatorsoup.com/calculators/conversions/kelvin-to-fahrenheit.php","Kelvin to Fahrenheit | K to °F"],
["https://www.calculatorsoup.com/calculators/conversions/kelvin-to-rankine.php","Kelvin to Rankin | K to °R"],
["https://www.calculatorsoup.com/calculators/conversions/kilograms-to-pounds.php","Kilograms to Pounds"],
["https://www.calculatorsoup.com/calculators/physics/kinetic.php","Kinetic Energy Calculator"],
["https://www.calculatorsoup.com/calculators/math/latticemultiplication.php","Lattice Multiplication Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/triangle-law-of-cosines.php","Law of Cosines Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/triangle-law-of-sines.php","Law of Sines Calculator"],
["https://www.calculatorsoup.com/calculators/financial/layaway-plan-calculator.php","Layaway Plan Calculator"],
["https://www.calculatorsoup.com/calculators/financial/liquidity-ratios-calculator.php","Liquidity Ratios Calculator"],
["https://www.calculatorsoup.com/calculators/math/lcd.php","LCD Calculator - Least Common Denominator"],
["https://www.calculatorsoup.com/calculators/math/lcm.php","LCM Calculator - Least Common Multiple"],
["https://www.calculatorsoup.com/calculators/financial/list-price-markdown-calculator.php","List Price Markdown Calculator"],
["https://www.calculatorsoup.com/calculators/financial/loan-calculator.php","Loan Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-loan-calculators.php","Loan and Mortgage Calculators"],
["https://www.calculatorsoup.com/calculators/financial/loan-payment-table.php","Loan Payment Table Generator"],
["https://www.calculatorsoup.com/calculators/financial/loan-repayment-calculator.php","Loan Repayment Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/logarithm-equation-calculator.php","Logarithm Equation Calculator"],
["https://www.calculatorsoup.com/calculators/math/long-addition-calculator.php","Long Addition Calculator"],
["https://www.calculatorsoup.com/calculators/math/long-subtraction-with-regrouping-calculator.php","Long Subtraction Calculator"],
["https://www.calculatorsoup.com/calculators/math/longdivisiondecimals.php","Long Division Calculator with Decimals"],
["https://www.calculatorsoup.com/calculators/math/longdivision.php","Long Division Calculator with Remainders"],
["https://www.calculatorsoup.com/calculators/math/longmultiplication.php","Long Multiplication Calculator"],
["https://www.calculatorsoup.com/calculators/games/lottery-number-generator.php","Lottery Number Generator"],
["https://www.calculatorsoup.com/calculators/financial/margin-calculator.php","Margin Calculator"],
["https://www.calculatorsoup.com/calculators/financial/markup-calculator.php","Mark-Up Calculator"],
["https://www.calculatorsoup.com/calculators/math/math.php","Math Calculator"],
["https://www.calculatorsoup.com/calculators/math/","Math Calculators"],
["https://www.calculatorsoup.com/calculators/math/math-equation-solver.php","Math Equation Solver"],
["https://www.calculatorsoup.com/calculators/wordproblems/mathwordproblem1.php","Math Word Problems: Addition &amp; Multiplication"],
["https://www.calculatorsoup.com/calculators/wordproblems/mathwordproblem2.php","Math Word Problems: Division"],
["https://www.calculatorsoup.com/calculators/statistics/average.php","Mean Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/mean-median-mode.php","Mean, Median, Mode Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/meters-to-feet.php","Meters to Feet Conversion"],
["https://www.calculatorsoup.com/calculators/conversions/metricunits.php","Metric Units Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/midpoint-calculator.php","Midpoint Calculator"],
["https://www.calculatorsoup.com/calculators/time/military-time-converter.php","Military Time Converter"],
["https://www.calculatorsoup.com/calculators/time/military-time-chart.php","Military Time Charts"],
["https://www.calculatorsoup.com/calculators/conversions/minutes-to-decimal.php","Minutes to Decimal Hours"],
["https://www.calculatorsoup.com/calculators/conversions/minutes-to-hours.php","Minutes to Hours Calculator"],
["https://www.calculatorsoup.com/calculators/math/mixednumbers.php","Mixed Numbers Calculator"],
["https://www.calculatorsoup.com/calculators/math/mixed-number-to-decimal-calculator.php","Mixed Number to Decimal Calculator"],
["https://www.calculatorsoup.com/calculators/math/mixed-number-to-percent-calculator.php","Mixed Number to Percent Calculator"],
["https://www.calculatorsoup.com/calculators/math/mixed-number-to-improper-fraction.php","Mixed Numbers to Improper Fractions"],
["https://www.calculatorsoup.com/calculators/chemistry/molecular-weight.php","Molecular Weight Calculator"],
["https://www.calculatorsoup.com/calculators/physics/momentum.php","Momentum Calculator p = mv"],
["https://www.calculatorsoup.com/calculators/conversions/momentum.php","Momentum Unit Converter (p)"],
["https://www.calculatorsoup.com/calculators/financial/money-calculator.php","Money Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-money-pay-taxes-calculators.php","Money, Pay and Tax Calculators"],
["https://www.calculatorsoup.com/calculators/financial/mortgage-calculator.php","Mortgage Calculator"],
["https://www.calculatorsoup.com/calculators/financial/mortgage-payment-calculator.php","Mortgage Payment Calculator"],
["https://www.calculatorsoup.com/calculators/financial/mortgage-repayment-calculator.php","Mortgage Repayment Calculator"],
["https://www.calculatorsoup.com/calculators/math/modulo-calculator.php","Modulo Calculator"],
["https://www.calculatorsoup.com/calculators/construction/mulch-calculator.php","Mulch Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/multifactorials.php","Multifactorial Calculator n! to n!!!!!"],
["https://www.calculatorsoup.com/calculators/math/multiples.php","Multiples Calculator"],
["https://www.calculatorsoup.com/calculators/math/multiplicationtables.php","Multiplication Tables Practice"],
["https://www.calculatorsoup.com/calculators/financial/net-present-value-calculator.php","Net Present Value Calculator"],
["https://www.calculatorsoup.com/calculators/games/draft-pick-value.php","NFL Draft Pick Value Calculator"],
["https://www.calculatorsoup.com/calculators/financial/nominal-interest-rate-calculator.php","Nominal Interest Rate Calculator"],
["https://www.calculatorsoup.com/calculators/math/number-word-notation-to-standard.php","Number and Word to Standard Notation Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/numberstowords.php","Numbers to Words Converter"],
["https://www.calculatorsoup.com/calculators/discretemathematics/oddpermutations.php","Odd Permutations Calculator"],
["https://www.calculatorsoup.com/calculators/games/odds.php","Odds Calculator"],
["https://www.calculatorsoup.com/calculators/financial/operations-ratios-calculator.php","Operations Ratios Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionsorder.php","Ordering Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/health/pace-calculator.php","Pace Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/parallelogram.php","Parallelogram Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/pascals-triangle.php","Pascal's Triangle Generator"],
["https://www.calculatorsoup.com/calculators/games/password-generator.php","Password Generator"],
["https://www.calculatorsoup.com/calculators/math/percent-to-decimal-calculator.php","Percent to Decimal Calculator"],
["https://www.calculatorsoup.com/calculators/math/percent-to-fraction-calculator.php","Percent to Fraction Calculator"],
["https://www.calculatorsoup.com/calculators/math/percentage.php","Percentage Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/percent-change-calculator.php","Percentage Change Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/percentage-increase-calculator.php","Percentage Increase Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/percentage-decrease-calculator.php","Percentage Decrease Calculator"],
["https://www.calculatorsoup.com/calculators/wordproblems/percentage-change-word-problem-1.php","Percentage Change Word Problems"],
["https://www.calculatorsoup.com/calculators/algebra/percent-difference-calculator.php","Percentage Difference Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/percent-error-calculator.php","Percentage Error Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/percentile-calculator.php","Percentile Calculator"],
["https://www.calculatorsoup.com/calculators/financial/compound-interest-calculator-periodic.php","Periodic Compound Interest Calculator"],
["https://www.calculatorsoup.com/calculators/financial/periodic-interest-rate-calculator.php","Periodic Interest Rate Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/permutationsreplacement.php","Permutation with Replacement Calculator"],
["https://www.calculatorsoup.com/calculators/discretemathematics/permutations.php","Permutations Calculator nPr"],
["https://www.calculatorsoup.com/calculators/financial/index-personal-finance-and-accounting.php","Personal Finance and Accounting Calculators"],
["https://www.calculatorsoup.com/calculators/physics/","Physics Calculators"],
["https://www.calculatorsoup.com/calculators/statistics/pin-generator.php","PIN Generator"],
["https://www.calculatorsoup.com/calculators/technology/ppi-calculator.php","Pixels per Inch PPI Calculator"],
["https://www.calculatorsoup.com/calculators/math/place-value-calculator.php","Place Value Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/","Plane Geometry Calculators"],
["https://www.calculatorsoup.com/calculators/games/poker.php","Poker 5 Card Draw"],
["https://www.calculatorsoup.com/calculators/games/poker-hands.php","Poker Hand Rankings"],
["https://www.calculatorsoup.com/help/pops.php","Pop Up Calculators"],
["https://www.calculatorsoup.com/calculators/conversions/pounds-to-kilograms.php","Pounds to Kilograms"],
["https://www.calculatorsoup.com/calculators/conversions/power.php","Power Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/financial/present-value-calculator-basic.php","Present Value Calculator (simple)"],
["https://www.calculatorsoup.com/calculators/financial/present-value-calculator.php","Present Value Calculator (comprehensive)"],
["https://www.calculatorsoup.com/calculators/financial/present-value-table-1.php","Present Value of $1 Table (PVIF)"],
["https://www.calculatorsoup.com/calculators/financial/present-value-table-annuity.php","Present Value of $1 Annuity Table (PVIFA)"],
["https://www.calculatorsoup.com/calculators/financial/present-value-investment-calculator.php","Present Value of a Future Sum Calculator"],
["https://www.calculatorsoup.com/calculators/financial/present-value-annuity-calculator.php","Present Value of Annuity Calculator"],
["https://www.calculatorsoup.com/calculators/financial/present-value-cash-flows-calculator.php","Present Value of Cash Flows Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/pressure.php","Pressure Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/physics/pressure.php","Pressure"],
["https://www.calculatorsoup.com/calculators/financial/price-calculator.php","Price Calculator"],
["https://www.calculatorsoup.com/calculators/math/prime-factors.php","Prime Factorization Calculator"],
["https://www.calculatorsoup.com/calculators/math/prime-number-calculator.php","Prime Number Calculator"],
["https://www.calculatorsoup.com/calculators/financial/profit-calculator.php","Profit Calculator"],
["https://www.calculatorsoup.com/calculators/financial/profit-goal-calculator.php","Profit Goal Calculator"],
["https://www.calculatorsoup.com/calculators/financial/profit-margin-calculator.php","Profit Margin Calculator"],
["https://www.calculatorsoup.com/calculators/financial/profitability-ratios-calculator.php","Profitability Ratios Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-property-realestate.php","Property Depreciation Calculator: Real Estate"],
["https://www.calculatorsoup.com/calculators/financial/property-tax-calculator.php","Property Tax Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/pythagorean-theorem.php","Pythagorean Theorem"],
["https://www.calculatorsoup.com/calculators/algebra/quadratic-formula-calculator.php","Quadratic Formula Calculator - 2nd Order Polynomial"],
["https://www.calculatorsoup.com/calculators/statistics/quartile-calculator.php","Quartile Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/radical.php","Radicals and Roots Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/random-card-generator.php","Random Card Generator"],
["https://www.calculatorsoup.com/calculators/statistics/random-name-picker.php","Random Name Picker"],
["https://www.calculatorsoup.com/calculators/statistics/random-number-generator.php","Random Number Generator"],
["https://www.calculatorsoup.com/calculators/statistics/random-number-generator-1-10.php","Random Number Generator 1-10"],
["https://www.calculatorsoup.com/calculators/statistics/random-number-generator-1-100.php","Random Number Generator 1-100"],
["https://www.calculatorsoup.com/calculators/statistics/number-generator.php","Random Number and Letter Set Generator"],
["https://www.calculatorsoup.com/calculators/math/ratios.php","Ratio Calculator"],
["https://www.calculatorsoup.com/calculators/math/ratio-to-fraction-calculator.php","Ratio to Fraction"],
["https://www.calculatorsoup.com/calculators/math/ratio-simplifier.php","Ratio Simplifier"],
["https://www.calculatorsoup.com/calculators/geometry-plane/rectangle.php","Rectangle Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/rectangularprism.php","Rectangular Prism Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/polygon.php","Regular Polygon Calculator"],
["https://www.calculatorsoup.com/calculators/financial/retirement-savings-calculator.php","Retirement Savings Calculator"],
["https://www.calculatorsoup.com/calculators/financial/return-on-investment-roi-calculator.php","Return on Investment ROI Calculator"],
["https://www.calculatorsoup.com/calculators/financial/sales-tax-calculator-reverse.php","Reverse Sales Tax Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/rhombus.php","Rhombus Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/triangles-right.php","Right Triangles Calculator"],
["https://www.calculatorsoup.com/calculators/construction/roadway.php","Roadway Fill Volume Calculator"],
["https://www.calculatorsoup.com/calculators/math/roundingnumbers.php","Rounding Numbers Calculator"],
["https://www.calculatorsoup.com/calculators/math/rounding-methods-calculator.php","Rounding Methods"],
["https://www.calculatorsoup.com/calculators/math/round-to-nearest-multiple.php","Round to Nearest Multiple"],
["https://www.calculatorsoup.com/calculators/financial/rule-of-72-calculator.php","Rule of 72 Calculator"],
["https://www.calculatorsoup.com/calculators/financial/sale-price-calculator.php","Sale Price Calculator"],
["https://www.calculatorsoup.com/calculators/financial/sales-calculator.php","Sales Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-sales-calculators.php","Sales and Retail Calculators"],
["https://www.calculatorsoup.com/calculators/financial/sales-tax-calculator.php","Sales Tax Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-savings-calculators.php","Saving and Investing Calculators"],
["https://www.calculatorsoup.com/calculators/financial/savings-calculator.php","Savings Calculator"],
["https://www.calculatorsoup.com/calculators/financial/savings-goal-calculator.php","Savings Goal Calculator"],
["https://www.calculatorsoup.com/scientific.php","Scientific Calculators"],
["https://www.calculatorsoup.com/calculators/math/scientificnotation.php","Scientific Notation Calculator"],
["https://www.calculatorsoup.com/calculators/math/scientific-notation-converter.php","Scientific Notation Converter"],
["https://www.calculatorsoup.com/calculators/financial/selling-price-calculator.php","Selling Price Calculator"],
["https://www.calculatorsoup.com/calculators/financial/service-tax-calculator-india.php","Service Tax Calculator India"],
["https://www.calculatorsoup.com/calculators/math/significant-figures.php","Significant Figures Calculator"],
["https://www.calculatorsoup.com/calculators/math/significant-figures-counter.php","Significant Figures Counter"],
["https://www.calculatorsoup.com/calculators/math/significant-figures-rounding.php","Significant Figures Rounding"],
["https://www.calculatorsoup.com/calculators/financial/simple-interest-plus-principal-calculator.php","Simple Interest Calculator A = P(1 + rt)"],
["https://www.calculatorsoup.com/calculators/financial/simple-interest-calculator.php","Simple Interest Calculator I = Prt"],
["https://www.calculatorsoup.com/calculators/financial/loan-calculator-simple.php","Simple Loan Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/radicals-simplify.php","Simplify Radical Expressions Calculator"],
["https://www.calculatorsoup.com/calculators/math/simplifying-complex-fractions-calculator.php","Simplifying Complex Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/math/fractionssimplify.php","Simplifying Fractions Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/slope-calculator.php","Slope Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/","Solid Geometry Calculators"],
["https://www.calculatorsoup.com/calculators/algebra/exponentsolve.php","Solve for Exponents Calculator"],
["https://www.calculatorsoup.com/calculators/math/speed-distance-time-calculator.php","Speed Calculator d = s × t"],
["https://www.calculatorsoup.com/calculators/conversions/speed.php","Speed Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/sphere.php","Sphere Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/squares.php","Square Calculator (geometry)"],
["https://www.calculatorsoup.com/calculators/algebra/square-calculator.php","Square Calculator for x²"],
["https://www.calculatorsoup.com/calculators/construction/square-footage-calculator.php","Square Footage Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/pyramid.php","Square Pyramid Calculator"],
["https://www.calculatorsoup.com/calculators/algebra/squareroots.php","Square Root Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/stadium.php","Stadium Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/standard-deviation-calculator.php","Standard Deviation Calculator"],
["https://www.calculatorsoup.com/calculators/math/standard-form-calculator.php","Standard Form Calculator"],
["https://www.calculatorsoup.com/calculators/financial/sales-tax-calculator-state-local.php","State and Local Sales Tax Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/statistics.php","Statistics Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/","Statistics Calculators"],
["https://www.calculatorsoup.com/calculators/statistics/stemleaf.php","Stem and Leaf Plot Generator"],
["https://www.calculatorsoup.com/calculators/financial/stock-ratios-calculator.php","Stock Ratios Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-straight-line.php","Straight Line Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-sum-of-years.php","Sum of Years Digits Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/sum-calculator.php","Sum Calculator"],
["https://www.calculatorsoup.com/calculators/time/sunrise_sunset.php","Sunrise Sunset Times"],
["https://www.calculatorsoup.com/calculators/geometry-solids/surfacearea.php","Surface Area Calculator"],
["https://www.calculatorsoup.com/calculators/construction/tank.php","Tank Volume Calculator"],
["https://www.calculatorsoup.com/calculators/health/target-heart-rate-zone-calculator.php","Target Heart Rate Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/temperature.php","Temperature Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/technology/","Technology Calculators"],
["https://www.calculatorsoup.com/calculators/time/","Time and Date Calculators"],
["https://www.calculatorsoup.com/calculators/time/time-date-difference-calculator.php","Time and Date Difference Calculator"],
["https://www.calculatorsoup.com/calculators/time/time-calculator.php","Time Calculator (+ − × ÷)"],
["https://www.calculatorsoup.com/calculators/time/hours-minutes-seconds.php","Time Calculator Hours:Minutes:Seconds"],
["https://www.calculatorsoup.com/calculators/financial/time-card-calculator.php","Time Card Calculator"],
["https://www.calculatorsoup.com/calculators/time/time-clock-calculator.php","Time Clock Calculator (Clock-in, Clock-out)"],
["https://www.calculatorsoup.com/calculators/conversions/time.php","Time Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/time/time-to-decimal-calculator.php","Time to Decimal Calculator"],
["https://www.calculatorsoup.com/calculators/financial/index-time-value-of-money-calculators.php","Time Value of Money Calculators"],
["https://www.calculatorsoup.com/calculators/financial/tip-calculator.php","Tip Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-plane/triangle-theorems.php","Triangle Theorems Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/triangular-prism.php","Triangular Prism Calculator"],
["https://www.calculatorsoup.com/calculators/trigonometry/graphs-trigonometricfunctions.php","Trigonometric Function Graphs F(x)"],
["https://www.calculatorsoup.com/calculators/trigonometry/graphs-trigonometricfunctions-pi.php","Trigonometric Function Graphs F(π)"],
["https://www.calculatorsoup.com/calculators/trigonometry/trigonometricfunctions.php","Trigonometric Functions Calculator"],
["https://www.calculatorsoup.com/calculators/trigonometry/trigonometricfunctions-pi.php","Trigonometric Functions Calculator ƒ(π)"],
["https://www.calculatorsoup.com/calculators/trigonometry/trigonometricratios.php","Trigonometric Ratios"],
["https://www.calculatorsoup.com/calculators/trigonometry/","Trigonometry Calculators"],
["https://www.calculatorsoup.com/calculators/conversions/weighttroy.php","Troy Weight Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/geometry-solids/tube.php","Tube Calculator"],
["https://www.calculatorsoup.com/calculators/physics/uniformly-accelerated-motion-calculator.php","Uniformly Accelerated Motion Calculator"],
["https://www.calculatorsoup.com/calculators/math/unit-rate-calculator.php","Unit Rate Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-units-production.php","Units of Production Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/financial/depreciation-variable-declining-balance.php","Variable Declining Balance Depreciation Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/variance-calculator.php","Variance Calculator"],
["https://www.calculatorsoup.com/calculators/physics/velocity-calculator-vuas.php","Velocity Calculator"],
["https://www.calculatorsoup.com/calculators/physics/velocity_a_t.php","Velocity as a Function of Acceleration and Time"],
["https://www.calculatorsoup.com/calculators/geometry-solids/volume.php","Volume Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/volume.php","Volume Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/vote-percentage-calculator.php","Vote Percentage Calculator"],
["https://www.calculatorsoup.com/calculators/physics/wavelength.php","Wavelength Calculator"],
["https://www.calculatorsoup.com/calculators/physics/weight.php","Weight Calculator"],
["https://www.calculatorsoup.com/calculators/conversions/weight.php","Weight (Mass) Conversion Calculator"],
["https://www.calculatorsoup.com/calculators/tools/what-is-my-ip-address.php","What is My IP Address?"],
["https://www.calculatorsoup.com/calculators/statistics/word-counter.php","Word Counter"],
["https://www.calculatorsoup.com/calculators/wordproblems/","Word Problems"],
["https://www.calculatorsoup.com/calculators/physics/work.php","Work Calculator (Physics)"],
["https://www.calculatorsoup.com/calculators/time/work-hours-calculator.php","Work Hours Calculator"],
["https://www.calculatorsoup.com/calculators/games/yugioh.php","Yu-Gi-Oh Calculator"],
["https://www.calculatorsoup.com/calculators/statistics/z-score-calculator.php","Z Score Calculator"],

["https://www.omnicalculator.com/biology/annealing-temperature","Annealing temperature"],["https://www.omnicalculator.com/biology/bacteria-growth","Bacteria growth"],["https://www.omnicalculator.com/biology/cell-dilution","Cell dilution"],["https://www.omnicalculator.com/biology/cell-doubling-time","Cell doubling time"],["https://www.omnicalculator.com/biology/dna-concentration","DNA concentration"],["https://www.omnicalculator.com/biology/ligation","Ligation"],["https://www.omnicalculator.com/biology/log-reduction","Log Reduction"],["https://www.omnicalculator.com/biology/allele-frequency","Allele frequency"],["https://www.omnicalculator.com/biology/dihybrid-cross-punnett-square","Dihybrid cross Punnett square"],["https://www.omnicalculator.com/biology/punnett-square","Punnett square"],["https://www.omnicalculator.com/biology/trihybrid-cross-punnett-square","Trihybrid cross Punnett square"],["https://www.omnicalculator.com/biology/cat-pregnancy","Cat pregnancy"],["https://www.omnicalculator.com/biology/cow-gestation","Cow gestation"],["https://www.omnicalculator.com/biology/dog-pregnancy","Dog pregnancy"],["https://www.omnicalculator.com/biology/goat-gestation","Goat gestation"],["https://www.omnicalculator.com/biology/guinea-pig-pregnancy","Guinea pig pregnancy"],["https://www.omnicalculator.com/biology/horse-gestation","Horse gestation"],["https://www.omnicalculator.com/biology/llama","Llama"],["https://www.omnicalculator.com/biology/rabbit-gestation","Rabbit gestation"],["https://www.omnicalculator.com/biology/sheep-gestation","Sheep gestation"],["https://www.omnicalculator.com/biology/swine-gestation","Swine gestation"],["https://www.omnicalculator.com/biology/benadryl-dosage-for-dogs","Benadryl dosage for dogs"],["https://www.omnicalculator.com/biology/cephalexin-for-dogs-dosage","Cephalexin for dogs dosage"],["https://www.omnicalculator.com/biology/dog-age","Dog age"],["https://www.omnicalculator.com/biology/dog-bmi","Dog BMI"],["https://www.omnicalculator.com/biology/dog-calorie","Dog calorie"],["https://www.omnicalculator.com/biology/dog-chocolate-toxicity","Dog chocolate toxicity"],["https://www.omnicalculator.com/biology/dog-crate-size","Dog crate size"],["https://www.omnicalculator.com/biology/dog-food","Dog food"],["https://www.omnicalculator.com/biology/dog-harness-size","Dog harness size"],["https://www.omnicalculator.com/biology/dog-heat-cycle","Dog heat cycle"],["https://www.omnicalculator.com/biology/dog-life-expectancy","Dog life expectancy"],["https://www.omnicalculator.com/biology/dog-metacam","Dog Metacam dosage"],["https://www.omnicalculator.com/biology/dog-onion-toxicity","Dog onion toxicity"],["https://www.omnicalculator.com/biology/dog-quality-of-life","Dog quality of life"],["https://www.omnicalculator.com/biology/dog-raisin-toxicity","Dog raisin toxicity"],["https://www.omnicalculator.com/biology/dog-size","Dog size"],["https://www.omnicalculator.com/biology/dog-water-intake","Dog water intake"],["https://www.omnicalculator.com/biology/omega-3-for-dogs","Omega-3 for dogs"],["https://www.omnicalculator.com/biology/the-cost-of-owning-a-dog","The cost of owning a dog"],["https://www.omnicalculator.com/biology/tramadol-for-dogs","Tramadol for dogs"],["https://www.omnicalculator.com/biology/cat-age","Cat age"],["https://www.omnicalculator.com/biology/cat-benadryl-dosage","Cat Benadryl dosage"],["https://www.omnicalculator.com/biology/cat-bmi","Cat BMI"],["https://www.omnicalculator.com/biology/cat-calorie","Cat calorie"],["https://www.omnicalculator.com/biology/cat-chocolate-toxicity","Cat chocolate toxicity"],["https://www.omnicalculator.com/biology/catculator","Catculator"],["https://www.omnicalculator.com/biology/cat-quality-of-life","Cat quality of life"],["https://www.omnicalculator.com/biology/fish-oil-dosage-for-cats","Fish oil dosage for cats"],["https://www.omnicalculator.com/biology/how-big-will-my-cat-get","How big will my cat get"],["https://www.omnicalculator.com/biology/metacam-dosage-cat","Metacam dosage for cats"],["https://www.omnicalculator.com/biology/bird-age","Bird age"],["https://www.omnicalculator.com/biology/cricket-chirp-thermometer","Crickets chirping thermometer"],["https://www.omnicalculator.com/biology/dry-matter","Dry matter"],["https://www.omnicalculator.com/biology/guinea-pig-age","Guinea pig years to human years"],["https://www.omnicalculator.com/biology/hamster-age","Hamster age"],["https://www.omnicalculator.com/biology/horse-weight","Horse weight"],["https://www.omnicalculator.com/biology/rabbit-cage-size","Rabbit cage size"],["https://www.omnicalculator.com/biology/rabbit-color","Rabbit color"],["https://www.omnicalculator.com/biology/rat-cage","Rat cage"],["https://www.omnicalculator.com/biology/turtle-tank","Turtle tank"],["https://www.omnicalculator.com/biology/animal-mortality-rate","Animal mortality rate"],["https://www.omnicalculator.com/biology/cattle-per-acre","Cattle per acre"],["https://www.omnicalculator.com/biology/fcr","Feed conversion ratio"],["https://www.omnicalculator.com/biology/grain-bin","Grain bin"],["https://www.omnicalculator.com/biology/livestock-fence","Livestock fence cost"],["https://www.omnicalculator.com/biology/acres-per-hour","Acres per hour"],["https://www.omnicalculator.com/biology/bulb-spacing","Bulb spacing"],["https://www.omnicalculator.com/biology/co2-grow-room","CO₂ grow room"],["https://www.omnicalculator.com/biology/compost","Compost"],["https://www.omnicalculator.com/biology/corn-yield","Corn yield"],["https://www.omnicalculator.com/biology/daily-light-integral-dli","Daily light integral (DLI)"],["https://www.omnicalculator.com/biology/fertilizer","Fertilizer"],["https://www.omnicalculator.com/biology/grass-seed","Grass seed"],["https://www.omnicalculator.com/biology/mowing-cost","Lawn mowing"],["https://www.omnicalculator.com/biology/mulch","Mulch"],["https://www.omnicalculator.com/biology/plant-population","Plant population"],["https://www.omnicalculator.com/biology/plants","Plant spacing"],["https://www.omnicalculator.com/biology/potting-soil-calculator","Potting soil"],["https://www.omnicalculator.com/biology/sod","Sod"],["https://www.omnicalculator.com/biology/soil","Soil"],["https://www.omnicalculator.com/biology/vapor-pressure-deficit","Vapor pressure deficit chart"],["https://www.omnicalculator.com/biology/vegetable-seed","Vegetable seed"],["https://www.omnicalculator.com/biology/vegetable-yield","Vegetable yield"],["https://www.omnicalculator.com/biology/water-potential","Water potential"],["https://www.omnicalculator.com/biology/water-soluble-fertilizer","Water soluble fertilizer"],["https://www.omnicalculator.com/biology/basal-area","Basal area"],["https://www.omnicalculator.com/biology/tree-leaves","Leaves on tree"],["https://www.omnicalculator.com/biology/tree-age","Tree age"],["https://www.omnicalculator.com/biology/tree-diameter","Tree diameter"],["https://www.omnicalculator.com/biology/tree-height","Tree height"],["https://www.omnicalculator.com/biology/tree-spacing","Tree spacing"],["https://www.omnicalculator.com/biology/tree-value","Tree value"],["https://www.omnicalculator.com/biology/mlvss","Mixed liquor volatile suspended solids"],["https://www.omnicalculator.com/biology/pet-sitter-rates","Pet sitter rates"],["https://www.omnicalculator.com/biology/protein-molecular-weight","Protein molecular weight"],["https://www.omnicalculator.com/biology/wastewater","Wastewater"],

["https://www.mathworks.com/","MathWorks, Makers of MATLAB and Simulink"],
["https://mathdf.com/dif/","Ordinary Differential Equation (ODE) and System of ODEs Calculator"],
["https://mathdf.com/int/","Integral Calculator"],
["https://mathdf.com/equ/","Equation, Inequality, and System of Equations Calculator"],
["https://mathdf.com/der/","Derivative Calculator"],
["https://mathdf.com/lim/","Limit Calculator"],
["https://mathdf.com/com/","Complex Numbers Calculator"],
["https://mathdf.com/mat/","Matrix Calculator"],

]
