articleLinks = articleLinks.concat([["Section 2.1 : Trig Function Evaluation","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/TrigFunctions.aspx"],
["Section 2.1 : Trig Function Evaluation","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/TrigFunctions.aspx#mm-17"],
["Section 2.2 : Linear Equations","https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx#mm-17"],
["Section 2.2 : Linear Equations","https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx#mm-26"],
["Section 16.5 : Fundamental Theorem For Line Integrals","https://tutorial.math.lamar.edu/Classes/CalcIII/FundThmLineIntegrals.aspx#mm-1"],
["Section 3.5 : Derivatives Of Trig Functions","https://tutorial.math.lamar.edu/Classes/CalcI/DiffTrigFcns.aspx"],
["Section 2.2 : Linear Equations","https://tutorial.math.lamar.edu/Classes/Alg/SolveLinearEqns.aspx#mm-6"],
["Section 3.6 : Combining Functions","https://tutorial.math.lamar.edu/Classes/Alg/CombineFunctions.aspx"],
["Section 7.8 : Improper Integrals","https://tutorial.math.lamar.edu/Classes/CalcII/ImproperIntegrals.aspx#mm-43"],
["Section 7.8 : Improper Integrals","https://tutorial.math.lamar.edu/Classes/CalcII/ImproperIntegrals.aspx#mm-2"],
["Chapter 12 : 3-Dimensional Space","https://tutorial.math.lamar.edu/Classes/CalcII/3DSpace.aspx"],
["Chapter 7 : Systems Of Equations","https://tutorial.math.lamar.edu/Classes/Alg/Systems.aspx"],
["Section 7.1 : Linear Systems With Two Variables","https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx"],
["Section 7.8 : Improper Integrals","https://tutorial.math.lamar.edu/Classes/CalcII/ImproperIntegrals.aspx#mm-24"],
["Section 7.8 : Improper Integrals","https://tutorial.math.lamar.edu/Classes/CalcII/ImproperIntegrals.aspx#mm-22"],
["Section 12.9 : Arc Length With Vector Functions","https://tutorial.math.lamar.edu/Classes/CalcIII/VectorArcLength.aspx"],
["Section 9.4 : Separation Of Variables","https://tutorial.math.lamar.edu/Classes/DE/SeparationofVariables.aspx"],
["HOW TO STUDY MATH","https://tutorial.math.lamar.edu/Extras/StudyMath/HowToStudyMath.aspx"],
["Section 10.2 : More On Sequences","https://tutorial.math.lamar.edu/Classes/CalcII/MoreSequences.aspx"],
["Section 4.6 : The Shape Of A Graph, Part II","https://tutorial.math.lamar.edu/Classes/CalcI/ShapeofGraphPtII.aspx"],
["5. Problem Solving","https://tutorial.math.lamar.edu/Extras/StudyMath/ProblemSolving.aspx"],
["1. General Errors","https://tutorial.math.lamar.edu/Extras/CommonErrors/GeneralErrors.aspx"],
["Section 4.8 : Optimization","https://tutorial.math.lamar.edu/Classes/CalcI/Optimization.aspx"],
["Section 1.2 : Absolute Value","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AbsoluteValue.aspx"],
["Section 7.1 : Linear Systems With Two Variables","https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx#mm-9"],
["Section 16.5 : Fundamental Theorem For Line Integrals","https://tutorial.math.lamar.edu/Classes/CalcIII/FundThmLineIntegrals.aspx"],
["Chapter 7 : Systems Of Equations","https://tutorial.math.lamar.edu/Classes/Alg/Systems.aspx#mm-0"],
["Section 1.11 : Solving Equations, Part II","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/SolveEqnPtII.aspx"],
["Chapter 7 : Systems Of Equations","https://tutorial.math.lamar.edu/Classes/Alg/Systems.aspx#mm-9"],
["Chapter 7 : Systems Of Equations","https://tutorial.math.lamar.edu/Classes/Alg/Systems.aspx#mm-31"],
["Chapter 7 : Systems Of Equations","https://tutorial.math.lamar.edu/Classes/Alg/Systems.aspx#mm-1"],
["Section 4.2 : Critical Points","https://tutorial.math.lamar.edu/Classes/CalcI/CriticalPoints.aspx"],
["Section 16.5 : Fundamental Theorem For Line Integrals","https://tutorial.math.lamar.edu/Classes/CalcIII/FundThmLineIntegrals.aspx#mm-31"],
["Section 2.1 : Trig Function Evaluation","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/TrigFunctions.aspx#mm-0"],
["1. General Errors","https://tutorial.math.lamar.edu/Extras/CommonErrors/GeneralErrors.aspx#mm-19"],
["1. General Errors","https://tutorial.math.lamar.edu/Extras/CommonErrors/GeneralErrors.aspx#mm-9"],
["Section 2.1 : Trig Function Evaluation","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/TrigFunctions.aspx#mm-24"],
["Section 1.6 : Solving Trig Equations With Calculators, Part II","https://tutorial.math.lamar.edu/Classes/CalcI/TrigEquations_CalcII.aspx"],
["Section 3.8 : Nonhomogeneous Differential Equations","https://tutorial.math.lamar.edu/Classes/DE/NonhomogeneousDE.aspx#mm-41"],
["Section 6.6 : Work","https://tutorial.math.lamar.edu/Classes/CalcI/Work.aspx#mm-36"],
["Section 9.8 : Vibrating String","https://tutorial.math.lamar.edu/Classes/DE/VibratingString.aspx"],
["Section 6.2 : Area Between Curves","https://tutorial.math.lamar.edu/Classes/CalcI/AreaBetweenCurves.aspx#mm-45"],
["Chapter 1 : Algebra Review","https://tutorial.math.lamar.edu/Extras/AlgebraTrigReview/AlgebraIntro.aspx"],
["Section 2.3 : Exact Equations","https://tutorial.math.lamar.edu/Classes/DE/Exact.aspx"],
["Section 7.1 : Linear Systems With Two Variables","https://tutorial.math.lamar.edu/Classes/Alg/SystemsTwoVrble.aspx#mm-19"],
["Section 11.2 : Vector Arithmetic","https://tutorial.math.lamar.edu/Classes/CalcII/VectorArithmetic.aspx"],
["Section 10.15 : Power Series And Functions","https://tutorial.math.lamar.edu/Classes/CalcII/PowerSeriesandFunctions.aspx"],
["Chapter 13 : Partial Derivatives","https://tutorial.math.lamar.edu/Classes/CalcIII/PartialDerivsIntro.aspx#mm-40"],
["Section 16.5 : Fundamental Theorem For Line Integrals","https://tutorial.math.lamar.edu/Classes/CalcIII/FundThmLineIntegrals.aspx#mm-0"],
["Section 12.1 : The 3-D Coordinate System","https://tutorial.math.lamar.edu/Classes/CalcIII/3DCoords.aspx"],
["Appendix A.6 : Area And Volume Formulas","https://tutorial.math.lamar.edu/Classes/CalcI/Area_Volume_Formulas.aspx"],
["Section 9.8 : Area With Polar Coordinates","https://tutorial.math.lamar.edu/Classes/CalcII/PolarArea.aspx"],
["Section 12.12 : Cylindrical Coordinates","https://tutorial.math.lamar.edu/Classes/CalcIII/CylindricalCoords.aspx#mm-47"],]);